const path = require('path');
const { resolvePython } = require('./python-path');

const PROJECT_ROOT = 'C:\\Project\\Image_scan';
const WEB_ROOT = path.join(PROJECT_ROOT, 'WEB-itinvent');
const PYTHON = resolvePython(PROJECT_ROOT);

module.exports = {
  apps: [
    {
      name: 'itinvent-backend',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_server.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 30000,
      restart_delay: 10000,
      kill_timeout: 15000,
      exp_backoff_restart_delay: 200,
      env: {
        HUBIT_RUNTIME_ROLE: 'api',
        BACKEND_HOST: '127.0.0.1',
        BACKEND_PORT: '8001',
        ANYIO_THREAD_TOKENS: '200',
        // Restored at the operator's request while interactive task work is diagnosed.
        APP_DB_POOL_SIZE: '20',
        APP_DB_MAX_OVERFLOW: '5',
        APP_DB_POOL_TIMEOUT: '30',
        APP_DB_APPLICATION_NAME: 'itinvent-backend',
        // Task discussions use the chat write engine from the API process.
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        // get_chat_read_engine has independent defaults; cap it explicitly too.
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_DB_POOL_TIMEOUT: '30',
        CHAT_DB_APPLICATION_NAME: 'itinvent-backend-nochat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-backend-chat-read',
        REQUEST_METRICS_ENABLED: '1',
        REQUEST_METRICS_LOCALHOST_OPEN: '1',
        REQUEST_METRICS_SLOW_MS: '1000',
        REQUEST_METRICS_MAX_ROUTES: '300',
        REQUEST_METRICS_SAMPLE_SIZE: '512',
        // Temporary browser/server JSONL diagnostics must stay opt-in in production.
        DEBUG_CLIENT_LOG_ENABLED: '0',
        LDAP_SYNC_BACKGROUND_ENABLED: '1',
        MFU_RUNTIME_MONITOR_ENABLED: '1',
        MAIL_MODULE_ENABLED: '1',
        MAIL_NOTIFICATION_BACKGROUND_ENABLED: '0',
        MAIL_EXCHANGE_MAX_CONCURRENCY: '16',
        MAIL_WORKER_THREADS: '16',
        MAIL_OFFICE_PREVIEW_MAX_CONCURRENCY: '2',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-chat',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_chat_server.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 30000,
      restart_delay: 10000,
      kill_timeout: 15000,
      exp_backoff_restart_delay: 200,
      env: {
        HUBIT_RUNTIME_ROLE: 'chat',
        BACKEND_HOST: '127.0.0.1',
        BACKEND_PORT: '8002',
        ANYIO_THREAD_TOKENS: '80',
        APP_DB_POOL_SIZE: '5',
        APP_DB_MAX_OVERFLOW: '3',
        APP_DB_POOL_TIMEOUT: '30',
        APP_DB_APPLICATION_NAME: 'itinvent-chat-auth',
        // Dual pools: write reserved for send; read capped separately.
        // write 12+2 + read 12+4 = 30 max per chat process (budget 40).
        // Four receipt slots remove the mark-read queue; two auxiliary slots keep
        // durable outbox work from competing too aggressively with message sends.
        CHAT_DB_WRITE_POOL_SIZE: '12',
        CHAT_DB_WRITE_MAX_OVERFLOW: '2',
        CHAT_DB_READ_POOL_SIZE: '12',
        CHAT_DB_READ_MAX_OVERFLOW: '4',
        CHAT_DB_CONNECTION_BUDGET: '40',
        CHAT_PROCESS_COUNT: '1',
        CHAT_SEND_DB_RESERVED: '4',
        CHAT_MARK_READ_DB_SLOTS: '4',
        CHAT_MARK_READ_PUBLISH_CONCURRENCY: '2',
        CHAT_AUX_WRITE_DB_SLOTS: '2',
        CHAT_READ_CONCURRENCY: '16',
        CHAT_READ_ACQUIRE_TIMEOUT_MS: '200',
        CHAT_READ_STATEMENT_TIMEOUT_MS: '5000',
        // Legacy aliases → write pool
        CHAT_DB_POOL_SIZE: '12',
        CHAT_DB_MAX_OVERFLOW: '2',
        CHAT_DB_POOL_TIMEOUT: '30',
        CHAT_DB_APPLICATION_NAME: 'itinvent-chat-write',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-chat-read',
        CHAT_WS_SEND_TIMEOUT_SEC: '5',
        // Chosen from worker sweep (zero-error best lag/ACK tradeoff).
        CHAT_WRITE_WORKERS: '16',
        CHAT_AFTER_SEND_HIGH_CONCURRENCY: '8',
        CHAT_AFTER_SEND_META_CONCURRENCY: '4',
        CHAT_AFTER_SEND_CONCURRENCY: '12',
        REQUEST_METRICS_ENABLED: '1',
        REQUEST_METRICS_LOCALHOST_OPEN: '1',
        REQUEST_METRICS_SLOW_MS: '1000',
        REQUEST_METRICS_MAX_ROUTES: '200',
        REQUEST_METRICS_SAMPLE_SIZE: '512',
        // Deep per-stage JSONL/stack profiling is opt-in for short diagnostics only.
        CHAT_AUDIT_ENABLED: '0',
        CHAT_PROFILE_STACK_ENABLED: '0',
        DEBUG_CLIENT_LOG_ENABLED: '0',
        CHAT_REDIS_CHANNEL: 'itinvent:chat:events',
        CHAT_PRESENCE_TTL_SEC: '75',
        CHAT_PRESENCE_TOUCH_THROTTLE_SEC: '15',
        CHAT_PRESENCE_WATCH_LIMIT: '50',
        CHAT_WS_COMMANDS_PER_SEC: '20',
        CHAT_WS_COMMAND_BURST: '40',
        CHAT_WS_OUTBOUND_QUEUE_SIZE: '256',
        CHAT_TYPING_STARTED_THROTTLE_SEC: '2',
        CHAT_TYPING_STATE_TTL_SEC: '5',
        CHAT_OUTBOX_CONCURRENCY: '4',
        LDAP_SYNC_BACKGROUND_ENABLED: '0',
        MFU_RUNTIME_MONITOR_ENABLED: '0',
        MAIL_MODULE_ENABLED: '0',
        MAIL_NOTIFICATION_BACKGROUND_ENABLED: '0',
        MAIL_OFFICE_PREVIEW_MAX_CONCURRENCY: '2',
        CHAT_NOTIFICATION_SIDEFX_WORKERS: '4',
        CHAT_NOTIFICATION_SIDEFX_CONCURRENCY: '4',
        CHAT_PUSH_SIDEFX_CONCURRENCY: '8',
        // Delivery is handled by itinvent-chat-push-worker only.
        CHAT_PUSH_OUTBOX_ENABLED: '0',
        // mark_read TP; DB slots capped separately (CHAT_MARK_READ_DB_SLOTS=4).
        CHAT_MARK_READ_WORKERS: '8',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-preview-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_preview_worker.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 15000,
      env: {
        MAIL_OFFICE_PREVIEW_ENABLED: '1',
        MAIL_OFFICE_PREVIEW_MAX_CONCURRENCY: '4',
        PREVIEW_WORKER_CONCURRENCY: '4',
        PREVIEW_MAX_ATTEMPTS: '3',
        PREVIEW_LEASE_SEC: '240',
        PREVIEW_POLL_INTERVAL_MS: '500',
        // The shared worker owns all document previews: Chat, Hub, mail,
        // document flow and My Files.
        // Preview work is intentionally isolated and capped below eight total DB connections.
        APP_DB_POOL_SIZE: '3',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-preview-worker',
        CHAT_DB_WRITE_POOL_SIZE: '2',
        CHAT_DB_WRITE_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_PROCESS_COUNT: '1',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_POOL_TIMEOUT: '30',
        CHAT_DB_APPLICATION_NAME: 'itinvent-preview-worker-chat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-preview-worker-chat-read',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-mail-notification-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_mail_notification_worker.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        MAIL_MODULE_ENABLED: '1',
        MAIL_NOTIFICATION_BACKGROUND_ENABLED: '1',
        CHAT_AUDIT_ENABLED: '0',
        CHAT_PROFILE_STACK_ENABLED: '0',
        DEBUG_CLIENT_LOG_ENABLED: '0',
        MAIL_NOTIFICATION_POLL_INTERVAL_SEC: '30',
        MAIL_NOTIFICATION_BATCH_SIZE: '50',
        MAIL_NOTIFICATION_MAX_CONCURRENCY: '8',
        MAIL_NOTIFICATION_USER_TIMEOUT_SEC: '15',
        MAIL_NOTIFICATION_CANDIDATE_TIMEOUT_SEC: '60',
        APP_DB_POOL_SIZE: '1',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-mail-worker',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_DB_APPLICATION_NAME: 'itinvent-mail-worker-chat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-mail-worker-chat-read',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-chat-push-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_chat_push_worker.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        CHAT_PUSH_OUTBOX_ENABLED: '1',
        CHAT_AUDIT_ENABLED: '0',
        CHAT_PROFILE_STACK_ENABLED: '0',
        DEBUG_CLIENT_LOG_ENABLED: '0',
        CHAT_PUSH_OUTBOX_POLL_INTERVAL_SEC: '2',
        CHAT_PUSH_OUTBOX_BATCH_SIZE: '25',
        CHAT_PUSH_OUTBOX_MAX_CONCURRENCY: '4',
        CHAT_PUSH_OUTBOX_MAX_ATTEMPTS: '8',
        CHAT_PUSH_OUTBOX_RETRY_BASE_SEC: '15',
        CHAT_PUSH_OUTBOX_PROCESSING_TIMEOUT_SEC: '300',
        CHAT_PUSH_OUTBOX_HEARTBEAT_SEC: '60',
        APP_DB_POOL_SIZE: '1',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-chat-push',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_DB_APPLICATION_NAME: 'itinvent-chat-push-chat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-chat-push-chat-read',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-ai-chat-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_ai_chat_worker.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        AI_CHAT_WORKER_CONCURRENCY: '2',
        CHAT_AUDIT_ENABLED: '0',
        CHAT_PROFILE_STACK_ENABLED: '0',
        DEBUG_CLIENT_LOG_ENABLED: '0',
        AI_KB_INDEX_FRESHNESS_TTL_SEC: '30',
        APP_DB_POOL_SIZE: '1',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-ai-chat-worker',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_DB_APPLICATION_NAME: 'itinvent-ai-chat-worker-chat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-ai-chat-worker-chat-read',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-my-files-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_my_files_worker.py',
      interpreter: 'none',
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        MY_FILES_INLINE_WORKER_ENABLED: '0',
        // Processing pool stays independent from the lifetime advisory-lock connection.
        APP_DB_POOL_SIZE: '4',
        APP_DB_MAX_OVERFLOW: '2',
        APP_DB_APPLICATION_NAME: 'itinvent-my-files-worker',
        APP_DB_DEDICATED_CONNECTIONS: '1',
        APP_DB_DEDICATED_APPLICATION_NAME: 'itinvent-my-files-worker-lock',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-hub-notifications-retention-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_hub_notifications_retention_worker.py',
      interpreter: 'none',
      windowsHide: true,
      // Off by default: enable only after dry-run review + HUB_NOTIFICATIONS_CLEANUP_ENABLED=true.
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        HUB_NOTIFICATIONS_CLEANUP_ENABLED: 'false',
        HUB_NOTIFICATIONS_CLEANUP_DRY_RUN: 'true',
        HUB_NOTIFICATIONS_CLEANUP_BATCH_SIZE: '50',
        HUB_NOTIFICATIONS_CLEANUP_BATCH_PAUSE_MS: '750',
        HUB_NOTIFICATIONS_CLEANUP_INTERVAL_SECONDS: '86400',
        HUB_NOTIFICATIONS_CLEANUP_STARTUP_DELAY_SECONDS: '120',
        APP_DB_POOL_SIZE: '1',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-hub-notifications-retention',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-chat-push-outbox-retention-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_chat_push_outbox_retention_worker.py',
      interpreter: 'none',
      windowsHide: true,
      instances: 1,
      // Off by default: dry-run only until Stage 0.5 restore gate + explicit execute approval.
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        CHAT_PUSH_OUTBOX_CLEANUP_ENABLED: 'false',
        CHAT_AUDIT_ENABLED: '0',
        CHAT_PROFILE_STACK_ENABLED: '0',
        DEBUG_CLIENT_LOG_ENABLED: '0',
        CHAT_PUSH_OUTBOX_CLEANUP_DRY_RUN: 'true',
        CHAT_PUSH_OUTBOX_CLEANUP_BATCH_SIZE: '200',
        CHAT_PUSH_OUTBOX_CLEANUP_BATCH_PAUSE_MS: '500',
        CHAT_PUSH_OUTBOX_CLEANUP_MAX_BATCHES: '100',
        CHAT_PUSH_OUTBOX_CLEANUP_MAX_RUNTIME_SECONDS: '120',
        CHAT_PUSH_OUTBOX_CLEANUP_INTERVAL_SECONDS: '3600',
        CHAT_PUSH_OUTBOX_CLEANUP_STARTUP_DELAY_SECONDS: '30',
        APP_DB_POOL_SIZE: '1',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-chat-push-outbox-retention-worker',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_DB_APPLICATION_NAME: 'itinvent-chat-push-outbox-retention',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-chat-push-outbox-retention-read',
        PYTHONUNBUFFERED: '1',
      },
    },
  ],
};
