const path = require('path');
const { resolvePython } = require('./python-path');

const PROJECT_ROOT = 'C:\\Project\\Image_scan';
const WEB_ROOT = path.join(PROJECT_ROOT, 'WEB-itinvent');
const PYTHON = resolvePython(PROJECT_ROOT);

function buildChatNode(name, port, nodeId) {
  return {
    name,
    cwd: WEB_ROOT,
    script: PYTHON,
    args: 'start_chat_server.py',
    interpreter: 'none',
    windowsHide: true,
    autorestart: true,
    max_restarts: 10,
    min_uptime: 30000,
    restart_delay: 10000,
    kill_timeout: 15000,
    exp_backoff_restart_delay: 200,
    env: {
      HUBIT_RUNTIME_ROLE: 'chat',
      BACKEND_HOST: '127.0.0.1',
      BACKEND_PORT: String(port),
      CHAT_REALTIME_NODE_ID: String(nodeId),
      // Scale-out must never accept traffic until the dedicated PostgreSQL
      // LISTEN connection is subscribed. /health/ready enforces this contract.
      CHAT_REALTIME_TRANSPORT: 'postgres',
      CHAT_REALTIME_REQUIRED: '1',
      // Do not inherit a legacy Redis fail-closed flag from the root .env.
      CHAT_REDIS_REQUIRED: '0',
      CHAT_PROCESS_COUNT: '2',
      ANYIO_THREAD_TOKENS: '64',

      APP_DB_POOL_SIZE: '2',
      APP_DB_MAX_OVERFLOW: '0',
      APP_DB_POOL_TIMEOUT: '30',
      APP_DB_APPLICATION_NAME: `${name}-auth`,

      // Per node: write 6+1 + read 5 = 12 pooled data connections plus
      // three dedicated PostgreSQL publisher/LISTEN/presence connections.
      // Two nodes use at most 30 chat-domain connections.
      CHAT_DB_WRITE_POOL_SIZE: '6',
      CHAT_DB_WRITE_MAX_OVERFLOW: '1',
      CHAT_DB_READ_POOL_SIZE: '5',
      CHAT_DB_READ_MAX_OVERFLOW: '0',
      CHAT_POSTGRES_REALTIME_DEDICATED_CONNECTIONS: '3',
      CHAT_DB_CONNECTION_BUDGET: '30',
      CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
      CHAT_DB_POOL_SIZE: '6',
      CHAT_DB_MAX_OVERFLOW: '1',
      CHAT_DB_POOL_TIMEOUT: '30',
      CHAT_DB_APPLICATION_NAME: `${name}-write`,
      CHAT_DB_READ_APPLICATION_NAME: `${name}-read`,
      CHAT_SEND_DB_RESERVED: '2',
      CHAT_MARK_READ_DB_SLOTS: '2',
      CHAT_MARK_READ_PUBLISH_CONCURRENCY: '2',
      CHAT_AUX_WRITE_DB_SLOTS: '1',
      CHAT_READ_CONCURRENCY: '7',
      CHAT_READ_ACQUIRE_TIMEOUT_MS: '250',
      CHAT_READ_STATEMENT_TIMEOUT_MS: '5000',

      CHAT_WRITE_WORKERS: '8',
      CHAT_AFTER_SEND_HIGH_CONCURRENCY: '4',
      CHAT_AFTER_SEND_META_CONCURRENCY: '2',
      CHAT_AFTER_SEND_CONCURRENCY: '6',
      CHAT_OUTBOX_CONCURRENCY: '2',
      CHAT_NOTIFICATION_SIDEFX_WORKERS: '2',
      CHAT_NOTIFICATION_SIDEFX_CONCURRENCY: '2',
      CHAT_PUSH_SIDEFX_CONCURRENCY: '4',
      CHAT_MARK_READ_WORKERS: '4',

      CHAT_WS_SEND_TIMEOUT_SEC: '5',
      CHAT_PRESENCE_TTL_SEC: '75',
      CHAT_PRESENCE_TOUCH_THROTTLE_SEC: '15',
      CHAT_PRESENCE_WATCH_LIMIT: '50',
      CHAT_WS_COMMANDS_PER_SEC: '20',
      CHAT_WS_COMMAND_BURST: '40',
      CHAT_WS_OUTBOUND_QUEUE_SIZE: '256',
      CHAT_TYPING_STARTED_THROTTLE_SEC: '2',
      CHAT_TYPING_STATE_TTL_SEC: '5',

      REQUEST_METRICS_ENABLED: '1',
      REQUEST_METRICS_LOCALHOST_OPEN: '1',
      REQUEST_METRICS_SLOW_MS: '1000',
      REQUEST_METRICS_MAX_ROUTES: '200',
      REQUEST_METRICS_SAMPLE_SIZE: '512',
      CHAT_AUDIT_ENABLED: '0',
      CHAT_PROFILE_STACK_ENABLED: '0',
      DEBUG_CLIENT_LOG_ENABLED: '0',

      LDAP_SYNC_BACKGROUND_ENABLED: '0',
      MFU_RUNTIME_MONITOR_ENABLED: '0',
      MAIL_MODULE_ENABLED: '0',
      MAIL_NOTIFICATION_BACKGROUND_ENABLED: '0',
      // Exactly one shared PM2 worker below owns push delivery.
      CHAT_PUSH_OUTBOX_ENABLED: '0',
      PYTHONUNBUFFERED: '1',
    },
  };
}

module.exports = {
  apps: [
    buildChatNode('itinvent-chat-a', 8002, 'chat-a'),
    buildChatNode('itinvent-chat-b', 8004, 'chat-b'),
    {
      name: 'itinvent-preview-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_preview_worker.py',
      interpreter: 'none',
      windowsHide: true,
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        MAIL_OFFICE_PREVIEW_ENABLED: '1',
        PREVIEW_WORKER_CONCURRENCY: '4',
        PREVIEW_MAX_ATTEMPTS: '3',
        PREVIEW_LEASE_SEC: '240',
        PREVIEW_POLL_INTERVAL_MS: '500',
        MAIL_OFFICE_PREVIEW_MAX_CONCURRENCY: '4',
        // 3 APP + 3 write + 1 read = 7 maximum connections for preview jobs.
        APP_DB_POOL_SIZE: '3',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-preview-worker',
        CHAT_DB_WRITE_POOL_SIZE: '2',
        CHAT_DB_WRITE_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_PROCESS_COUNT: '1',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_APPLICATION_NAME: 'itinvent-preview-worker-chat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-preview-worker-read',
        PYTHONUNBUFFERED: '1',
      },
    },
    {
      name: 'itinvent-chat-push-worker',
      cwd: WEB_ROOT,
      script: PYTHON,
      args: 'start_chat_push_worker.py',
      interpreter: 'none',
      windowsHide: true,
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        CHAT_PUSH_OUTBOX_ENABLED: '1',
        CHAT_AUDIT_ENABLED: '0',
        CHAT_PROFILE_STACK_ENABLED: '0',
        DEBUG_CLIENT_LOG_ENABLED: '0',
        CHAT_PUSH_OUTBOX_POLL_INTERVAL_SEC: '2',
        CHAT_PUSH_OUTBOX_BATCH_SIZE: '25',
        CHAT_PUSH_OUTBOX_MAX_CONCURRENCY: '4',
        CHAT_PUSH_OUTBOX_MAX_ATTEMPTS: '8',
        CHAT_PUSH_OUTBOX_RETRY_BASE_SEC: '15',
        CHAT_PUSH_OUTBOX_PROCESSING_TIMEOUT_SEC: '300',
        CHAT_PUSH_OUTBOX_HEARTBEAT_SEC: '60',
        APP_DB_POOL_SIZE: '1',
        APP_DB_MAX_OVERFLOW: '0',
        APP_DB_APPLICATION_NAME: 'itinvent-chat-push',
        CHAT_DB_POOL_SIZE: '2',
        CHAT_DB_MAX_OVERFLOW: '1',
        CHAT_DB_READ_POOL_SIZE: '1',
        CHAT_DB_READ_MAX_OVERFLOW: '0',
        CHAT_DB_CONNECTION_BUDGET: '4',
        CHAT_DB_CONNECTION_BUDGET_FAIL_START: '1',
        CHAT_DB_APPLICATION_NAME: 'itinvent-chat-push-chat',
        CHAT_DB_READ_APPLICATION_NAME: 'itinvent-chat-push-chat-read',
        PYTHONUNBUFFERED: '1',
      },
    },
  ],
};
