import { describe, expect, it } from 'vitest';

import buildChatPagePanesBags from './buildChatPagePanesBags';

describe('buildChatPagePanesBags', () => {
  it('groups pane props into shell, sidebar, thread and rightPanel bags', () => {
    const input = {
      theme: { palette: {} },
      ui: { pageBg: '#fff' },
      isMobile: true,
      isPhone: true,
      mobileMotionDisabled: false,
      health: { ok: true },
      user: { id: 'u1' },
      unreadTotal: 3,
      sidebarQuery: '',
      setSidebarQuery: () => {},
      sidebarSearchActive: false,
      searchingSidebar: false,
      searchPeople: [],
      searchChats: [],
      searchResultEmpty: false,
      openingPeerId: '',
      handleOpenPeer: () => {},
      activeConversationId: 'c1',
      openConversation: () => {},
      prefetchThreadBootstrap: () => {},
      conversationsLoading: false,
      filteredConversations: [],
      openGroupDialog: () => {},
      sidebarScrollRef: { current: null },
      conversationFilter: 'all',
      handleActiveFolderChange: () => {},
      customFolders: [],
      conversationFilterCounts: {},
      conversationIdsByFolder: {},
      handleOpenFolderManager: () => {},
      handleOpenArchiveFolder: () => {},
      handleToggleConversationInFolder: () => {},
      draftsByConversation: {},
      updateConversationSettings: () => {},
      requestDeleteConversation: () => {},
      requestLeaveConversation: () => {},
      conversationActionPendingId: '',
      aiSidebarRows: [],
      aiBotsLoading: false,
      aiBotsError: '',
      canUseAiChat: true,
      handleOpenAiBot: () => {},
      openingAiBotId: '',
      activeConversation: { id: 'c1' },
      navigate: () => {},
      threadWallpaperSx: {},
      messages: [],
      messagesLoading: false,
      effectiveLastReadMessageId: '',
      showOlderHistoryControl: false,
      loadingOlder: false,
      prependScrollRestoreRef: { current: null },
      loadOlderMessages: () => {},
      threadScrollRef: { current: null },
      threadContentRef: { current: null },
      handleThreadScroll: () => {},
      bottomRef: { current: null },
      openMobileInboxView: () => {},
      handleOpenInfo: () => {},
      openTaskFromChat: () => {},
      openSearchDialog: () => {},
      handleOpenMenu: () => {},
      openMessageReads: () => {},
      openMediaViewer: () => {},
      handleReplyMessage: () => {},
      openMessageMenu: () => {},
      confirmAiAction: () => {},
      cancelAiAction: () => {},
      editAiAction: () => {},
      selectedVisibleMessageIds: [],
      selectedMessageCount: 0,
      canCopySelectedMessages: false,
      toggleMessageSelection: () => {},
      startMessageSelection: () => {},
      clearSelectedMessages: () => {},
      selectedReplyToSelectedMessage: () => {},
      selectedCopySelectedMessages: () => {},
      selectedOpenForwardSelectedMessages: () => {},
      handleOpenComposerMenu: () => {},
      composerRef: { current: null },
      messageText: '',
      setMessageText: () => {},
      handleComposerKeyDown: () => {},
      syncComposerSelection: () => {},
      handleOpenEmojiPicker: () => {},
      handleCloseEmojiPicker: () => {},
      handleComposerFocusChange: () => {},
      handleComposerSend: () => {},
      handleComposerPaste: () => {},
      handleComposerDrop: () => {},
      handleComposerDragOver: () => {},
      handleComposerDragLeave: () => {},
      mentionCandidates: [],
      searchMentionPeople: () => {},
      fileDragActive: false,
      showJumpToLatest: false,
      jumpToLatest: () => {},
      replyMessage: null,
      clearReplyMessage: () => {},
      editingMessage: null,
      clearEditingMessage: () => {},
      aiTypingStatus: '',
      activeAiStatus: null,
      pinnedMessage: null,
      handleOpenPinnedMessage: () => {},
      handleUnpinPinnedMessage: () => {},
      highlightedMessageId: '',
      conversationMetaSubtitle: '',
      aiAwareTypingLine: '',
      renderDesktopRightPanel: false,
      selectedFiles: [],
      fileCaption: '',
      openFilePicker: () => {},
      clearSelectedFiles: () => {},
      preparingFiles: false,
      sendingFiles: false,
      fileUploadProgress: 0,
      selectedFilesSummary: null,
      getReadTargetRef: () => null,
      handleToggleReaction: () => {},
      scrollToMessage: () => {},
      emojiPickerOpen: false,
      insertEmojiAtSelection: () => {},
      handleSendGif: () => {},
      voiceRecording: false,
      voiceRecordingDuration: 0,
      voiceRecordingLevelRef: { current: 0 },
      startVoiceRecording: () => {},
      stopVoiceRecording: () => {},
      cancelVoiceRecording: () => {},
      bindPinnedScroll: () => {},
      showTaskPanel: false,
      showContextPanel: false,
      taskPanelTaskId: '',
      closeTaskPanel: () => {},
      openTaskInTasks: () => {},
      handleTaskPanelUpdated: () => {},
      setContextPanelOpen: () => {},
      openShareDialog: () => {},
      handleAddGroupMembers: () => {},
      handleRemoveGroupMember: () => {},
      handleUpdateGroupMemberRole: () => {},
      handleTransferGroupOwnership: () => {},
      handleLeaveGroup: () => {},
      handleUpdateGroupProfile: () => {},
      settingsUpdating: false,
      socketStatus: 'connected',
    };

    const bags = buildChatPagePanesBags(input);

    expect(bags.shell.isMobile).toBe(true);
    expect(bags.sidebar.activeConversationId).toBe('c1');
    expect(bags.thread.activeConversationId).toBe('c1');
    expect(bags.thread.messages).toEqual([]);
    expect(bags.rightPanel.socketStatus).toBe('connected');
  });
});
