import { describe, expect, it } from 'vitest';

import { pickChatPageLayoutSections } from './pickChatPageLayoutSections';

describe('pickChatPageLayoutSections', () => {
  it('groups shell and sidebar keys for domain sections', () => {
    const input = {
      theme: { palette: {} },
      ui: { pageBg: '#fff' },
      isMobile: true,
      isPhone: true,
      mobileMotionDisabled: false,
      health: { ok: true },
      user: { id: 1 },
      unreadTotal: 0,
      sidebarQuery: '',
      setSidebarQuery: () => {},
      sidebarSearchActive: false,
      searchingSidebar: false,
      searchPeople: [],
      searchChats: [],
      searchResultEmpty: false,
      openingPeerId: '',
      handleOpenPeer: () => {},
      activeConversationId: 'c1',
      openConversation: () => {},
      prefetchThreadBootstrap: () => {},
      conversationsLoading: false,
      filteredConversations: [],
      openGroupDialog: () => {},
      sidebarScrollRef: { current: null },
      conversationFilter: 'all',
      handleActiveFolderChange: () => {},
      customFolders: [],
      conversationFilterCounts: {},
      conversationIdsByFolder: {},
      handleOpenFolderManager: () => {},
      handleOpenArchiveFolder: () => {},
      handleToggleConversationInFolder: () => {},
      draftsByConversation: {},
      updateConversationSettings: () => {},
      requestDeleteConversation: () => {},
      requestLeaveConversation: () => {},
      conversationActionPendingId: '',
      aiSidebarRows: [],
      aiBotsLoading: false,
      aiBotsError: '',
      canUseAiChat: false,
      handleOpenAiBot: () => {},
      openingAiBotId: '',
      activeConversation: null,
      navigate: () => {},
      threadWallpaperSx: {},
      messages: [],
      messagesLoading: false,
      effectiveLastReadMessageId: '',
      showOlderHistoryControl: false,
      loadingOlder: false,
      prependScrollRestoreRef: { current: null },
      loadOlderMessages: () => {},
      threadScrollRef: { current: null },
      threadContentRef: { current: null },
      handleThreadScroll: () => {},
      bottomRef: { current: null },
      openMobileInboxView: () => {},
      handleOpenInfo: () => {},
      openTaskFromChat: () => {},
      openSearchDialog: () => {},
      handleOpenMenu: () => {},
      openMessageReads: () => {},
      openMediaViewer: () => {},
      handleReplyMessage: () => {},
      openMessageMenu: () => {},
      confirmAiAction: () => {},
      cancelAiAction: () => {},
      editAiAction: () => {},
      selectedVisibleMessageIds: [],
      selectedMessageCount: 0,
      canCopySelectedMessages: false,
      toggleMessageSelection: () => {},
      startMessageSelection: () => {},
      clearSelectedMessages: () => {},
      selectedReplyToSelectedMessage: () => {},
      selectedCopySelectedMessages: () => {},
      selectedOpenForwardSelectedMessages: () => {},
      handleOpenComposerMenu: () => {},
      composerRef: { current: null },
      messageText: '',
      setMessageText: () => {},
      handleComposerKeyDown: () => {},
      syncComposerSelection: () => {},
      handleOpenEmojiPicker: () => {},
      handleCloseEmojiPicker: () => {},
      handleComposerFocusChange: () => {},
      handleComposerSend: () => {},
      handleComposerPaste: () => {},
      handleComposerDrop: () => {},
      handleComposerDragOver: () => {},
      handleComposerDragLeave: () => {},
      mentionCandidates: [],
      searchMentionPeople: () => {},
      fileDragActive: false,
      showJumpToLatest: false,
      jumpToLatest: () => {},
      replyMessage: null,
      clearReplyMessage: () => {},
      editingMessage: null,
      clearEditingMessage: () => {},
      aiTypingStatus: null,
      activeAiStatus: null,
      pinnedMessage: null,
      handleOpenPinnedMessage: () => {},
      handleUnpinPinnedMessage: () => {},
      highlightedMessageId: '',
      conversationMetaSubtitle: '',
      aiAwareTypingLine: '',
      renderDesktopRightPanel: false,
      selectedFiles: [],
      fileCaption: '',
      openFilePicker: () => {},
      clearSelectedFiles: () => {},
      preparingFiles: false,
      sendingFiles: false,
      fileUploadProgress: 0,
      selectedFilesSummary: '',
      getReadTargetRef: () => ({ current: null }),
      handleToggleReaction: () => {},
      scrollToMessage: () => {},
      emojiPickerOpen: false,
      insertEmojiAtSelection: () => {},
      handleSendGif: () => {},
      voiceRecording: false,
      voiceRecordingDuration: 0,
      voiceRecordingLevelRef: { current: 0 },
      startVoiceRecording: () => {},
      stopVoiceRecording: () => {},
      cancelVoiceRecording: () => {},
      bindPinnedScroll: () => {},
      showTaskPanel: false,
      showContextPanel: false,
      taskPanelTaskId: '',
      closeTaskPanel: () => {},
      openTaskInTasks: () => {},
      handleTaskPanelUpdated: () => {},
      setContextPanelOpen: () => {},
      openShareDialog: () => {},
      handleAddGroupMembers: () => {},
      handleRemoveGroupMember: () => {},
      handleUpdateGroupMemberRole: () => {},
      handleTransferGroupOwnership: () => {},
      handleLeaveGroup: () => {},
      handleUpdateGroupProfile: () => {},
      settingsUpdating: false,
      socketStatus: 'offline',
      currentUser: { id: 1 },
      threadMenuAnchor: null,
      setThreadMenuAnchor: () => {},
      infoOpen: false,
      messageMenuAnchor: null,
      messageMenuMessage: null,
      closeMessageMenu: () => {},
      handleReplyFromMessageMenu: () => {},
      handleCopyMessage: () => {},
      handleTogglePinMessageFromMenu: () => {},
      handleCopyMessageLink: () => {},
      forwardHookMessageFromMenu: () => {},
      handleReportMessageFromMenu: () => {},
      handleDeleteMessageFromMenu: () => {},
      handleEditFromMessageMenu: () => {},
      handleSelectMessageFromMenu: () => {},
      handleOpenReadsFromMessageMenu: () => {},
      handleOpenAttachmentFromMessageMenu: () => {},
      handleOpenTaskFromMessageMenu: () => {},
      composerMenuAnchor: null,
      setComposerMenuAnchor: () => {},
      openMediaPicker: () => {},
      emojiAnchorEl: null,
      mediaFileInputRef: { current: null },
      handleSelectFiles: () => {},
      fileInputRef: { current: null },
      fileDialogOpen: false,
      closeFileDialog: () => {},
      setFileCaption: () => {},
      sendFiles: () => {},
      removeSelectedFile: () => {},
      groupOpen: false,
      closeGroupDialog: () => {},
      groupTitle: '',
      setGroupTitle: () => {},
      groupSearch: '',
      setGroupSearch: () => {},
      groupUsers: [],
      groupUsersLoading: false,
      groupSelectedUsers: [],
      groupMemberIds: [],
      addGroupMember: () => {},
      removeGroupMember: () => {},
      creatingConversation: false,
      groupCreateDisabled: false,
      createGroup: () => {},
      shareOpen: false,
      resetShareDialog: () => {},
      taskSearch: '',
      setTaskSearch: () => {},
      shareableTasks: [],
      shareableLoading: false,
      sharingTaskId: '',
      shareTaskFromHook: () => {},
      forwardOpen: false,
      closeForwardDialog: () => {},
      forwardMessages: [],
      forwardConversationQuery: '',
      setForwardConversationQuery: () => {},
      forwardTargets: [],
      forwardingConversationId: '',
      forwardHookMessageToConversation: () => {},
      attachmentPreview: null,
      closeAttachmentPreview: () => {},
      documentPreview: null,
      closeDocumentPreview: () => {},
      handleDownloadDocumentPreview: () => {},
      handleDownloadDocumentPreviewPdf: () => {},
      messageReadsOpen: false,
      setMessageReadsOpen: () => {},
      messageReadsMessage: null,
      messageReadsLoading: false,
      messageReadsItems: [],
      closeMobileInfoView: () => {},
      requestConversationRemoval: () => {},
      searchOpen: false,
      closeSearchDialog: () => {},
      messageSearch: '',
      setMessageSearch: () => {},
      messageSearchResults: [],
      messageSearchLoading: false,
      messageSearchHasMore: false,
      loadMoreSearchResults: () => {},
      openSearchResult: () => {},
    };

    const sections = pickChatPageLayoutSections(input);
    expect(sections.shell.theme).toBe(input.theme);
    expect(sections.sidebar.activeConversationId).toBe('c1');
    expect(sections.thread.messageText).toBe('');
    expect(sections.dialogs.searchOpen).toBe(false);
  });
});
