import useChatPageController from './useChatPageController';
import useChatFolderMutationsController from './useChatFolderMutationsController';
import { CHAT_SWR_STALE_TIME_MS } from './chatPageConstants';

export default function useChatPageCoreBridge({
  activeConversationId,
  refs,
  initialConversationId,
  initialThreadCache,
  conversationsCacheKeyParts,
  userCacheId,
  notifyApiError,
  setConversations,
  setConversationsLoading,
  setCustomFolders,
  setConversationIdsByFolder,
  setFoldersLoading,
  setConversationFilter,
  canUseAiChat,
  aiBotsCacheKeyParts,
  setAiBots,
  setAiBotsLoading,
  setAiBotsError,
  setAiStatusByConversation,
  user,
  messageText,
  pinnedMessage,
  setPinnedMessage,
  conversationFilter,
  customFolders,
  setFolderManagerCreateMode,
  setFolderManagerOpen,
  setFolderSaving,
}) {
  const {
    activeConversationIdRef,
    autoScrollMetaRef,
    autoScrollRef,
    cancelPendingInitialAnchorRef,
    capturePrependScrollRestoreRef,
    conversationsRef,
    hasPendingInitialAnchorForConversationRef,
    hydratedThreadConversationIdRef,
    isInitialViewportGuardActiveRef,
    loadOlderInFlightCursorRef,
    logChatDebugRef,
    prependScrollRestoreRef,
    resolvePendingInitialAnchorFromPayloadRef,
    scrollThreadBottomIntoViewRef,
    scrollToMessageRef,
    showJumpToLatestRef,
    syncConversationPreviewRef,
    threadLoadAbortRef,
    threadNearBottomRef,
    threadPrefetchAbortControllersRef,
    conversationsCacheHydratedRef,
    conversationsLoadingRef,
    conversationsLoadingRequestSeqRef,
    conversationsRequestSeqRef,
    lastConversationsLoadAtRef,
    sidebarScrollRef,
    aiBotsRequestSeqRef,
    aiBotsLoadingRequestSeqRef,
    aiBotsLoadingRef,
    aiBotsCacheHydratedRef,
    suppressDraftSyncRef,
    draftWriteTimeoutRef,
    latestDraftStorageKeyRef,
    latestMessageTextRef,
    loadConversationsRef,
    setShowJumpToLatest,
  } = refs;

  const {
    thread: threadController,
    sidebar: sidebarController,
    folders: foldersController,
    ai: aiController,
    drafts: draftsController,
  } = useChatPageController({
    thread: {
      activeConversationId,
      activeConversationIdRef,
      autoScrollMetaRef,
      autoScrollRef,
      cancelPendingInitialAnchorRef,
      capturePrependScrollRestoreRef,
      conversationsRef,
      hasPendingInitialAnchorForConversationRef,
      hydratedThreadConversationIdRef,
      initialConversationId,
      initialThreadCache,
      isInitialViewportGuardActiveRef,
      loadOlderInFlightCursorRef,
      logChatDebugRef,
      notifyApiError,
      prependScrollRestoreRef,
      resolvePendingInitialAnchorFromPayloadRef,
      scrollThreadBottomIntoViewRef,
      scrollToMessageRef,
      setShowJumpToLatest,
      showJumpToLatestRef,
      syncConversationPreviewRef,
      threadLoadAbortRef,
      threadNearBottomRef,
      threadPrefetchAbortControllersRef,
      userCacheId,
    },
    conversations: {
      conversationsCacheHydratedRef,
      conversationsCacheKeyParts,
      conversationsLoadingRef,
      conversationsLoadingRequestSeqRef,
      conversationsRef,
      conversationsRequestSeqRef,
      lastConversationsLoadAtRef,
      loadConversationsRef,
      notifyApiError,
      setConversations,
      setConversationsLoading,
      sidebarScrollRef,
      staleTimeMs: CHAT_SWR_STALE_TIME_MS,
      userCacheId,
    },
    folders: {
      conversationFilter,
      customFolders,
      notifyApiError,
      setConversationFilter,
      setConversationIdsByFolder,
      setCustomFolders,
      setFolderManagerCreateMode,
      setFolderManagerOpen,
      setFolderSaving,
      setFoldersLoading,
    },
    ai: canUseAiChat
      ? {
          aiBotsCacheHydratedRef,
          aiBotsCacheKeyParts,
          aiBotsLoadingRef,
          aiBotsLoadingRequestSeqRef,
          aiBotsRequestSeqRef,
          canUseAiChat,
          notifyApiError,
          setAiBots,
          setAiBotsError,
          setAiBotsLoading,
          setAiStatusByConversation,
          staleTimeMs: CHAT_SWR_STALE_TIME_MS,
          userCacheId,
        }
      : undefined,
    drafts: {
      activeConversationId,
      draftWriteTimeoutRef,
      latestDraftStorageKeyRef,
      latestMessageTextRef,
      messageText,
      pinnedMessage,
      setPinnedMessage,
      suppressDraftSyncRef,
      userId: user?.id,
    },
  });

  const {
    loadConversations,
    applyConversationsPayload,
    handleSidebarScroll,
  } = sidebarController;

  const {
    loadChatFolders,
    handleActiveFolderChange,
    applyFoldersPayload,
    restoreFolderFilter,
  } = foldersController;

  const {
    loadAiBots,
    applyAiBotsPayload,
    fetchConversationAiStatus,
  } = aiController || {};

  const {
    draftStorageKey,
    pinnedStorageKey,
    flushDraftToStorage,
    persistPinnedMessage,
  } = draftsController;

  const folderMutations = useChatFolderMutationsController({
    conversationFilter,
    customFolders,
    handleActiveFolderChange,
    loadChatFolders,
    notifyApiError,
    setFolderManagerCreateMode,
    setFolderManagerOpen,
    setFolderSaving,
  });

  return {
    ...threadController,
    loadConversations,
    applyConversationsPayload,
    handleSidebarScroll,
    loadChatFolders,
    handleActiveFolderChange,
    applyFoldersPayload,
    restoreFolderFilter,
    loadAiBots,
    applyAiBotsPayload,
    fetchConversationAiStatus,
    draftStorageKey,
    pinnedMessageStorageKey: pinnedStorageKey,
    flushDraftToStorage,
    persistPinnedMessageToStorage: persistPinnedMessage,
    ...folderMutations,
  };
}
