import useChatActiveThreadPolling from '../../components/chat/useChatActiveThreadPolling';
import useChatAiStatusPolling from '../../components/chat/useChatAiStatusPolling';
import { useChatSocketControllerEvents } from './useChatSocketController';
import { mergeAiStatusPayload, shouldPollActiveAiThread } from './chatAiModel';
import {
  buildActiveThreadPollLoadOptions,
  shouldPollActiveThreadIncrementally,
  shouldSkipActiveThreadRevalidate,
} from './chatThreadTransport';
import { hasPersistedThreadMessageEquivalent } from './chatThreadMessages';
import {
  CHAT_AI_ACTIVE_POLL_MS,
  CHAT_AI_ACTIVE_POLL_WS_CONNECTED_MS,
  CHAT_ACTIVE_THREAD_INCREMENTAL_POLL_MS,
  CHAT_LIST_POLL_MS,
  CHAT_THREAD_POLL_MS,
} from './chatPageConstants';

export default function useChatPageRealtimeEffects({
  activeConversationId,
  activeConversation,
  activeConversationIdRef,
  activeThreadTransportState,
  activeAiStatus,
  canUseAiChat,
  conversationBootstrapComplete,
  degradedThreadRevalidateCountRef,
  incrementalPollMs = CHAT_ACTIVE_THREAD_INCREMENTAL_POLL_MS,
  lastConversationsLoadAtRef,
  lastForegroundRefreshAtRef,
  listPollMs = CHAT_LIST_POLL_MS,
  loadConversations,
  loadMessages,
  loadMessagesRef,
  logChatDebug,
  logChatDebugRef,
  messagesLoadingRef,
  messagesRef,
  sidebarSearchActive,
  socketStatus,
  threadPollMs = CHAT_THREAD_POLL_MS,
  aiRunStartedAtByConversationRef,
  applyMessageReadDelta,
  conversationsLoadingRef,
  hasPendingInitialAnchorForConversation,
  latestActiveThreadSocketMessageRef,
  markConversationReadLiveRef,
  markSocketActivity,
  mergeMessageIntoThread,
  onConversationRemoved,
  promoteConversationToTop,
  queueAutoScroll,
  setAiStatusByConversation,
  setMessages,
  setSocketStatus,
  setTypingUsers,
  setViewerLastReadAt,
  setViewerLastReadMessageId,
  skippedInitialSnapshotRefreshRef,
  skippedInitialSocketRefreshRef,
  socketStatusRef,
  syncConversationPreview,
  threadNearBottomRef,
  typingParticipantsTimeoutsRef,
  updatePresenceInCollections,
  upsertConversation,
  userId,
}) {
  useChatActiveThreadPolling({
    activeConversationId,
    activeConversationIdRef,
    activeThreadTransportState,
    buildActiveThreadPollLoadOptions,
    conversationBootstrapComplete,
    degradedThreadRevalidateCountRef,
    incrementalPollMs,
    lastConversationsLoadAtRef,
    lastForegroundRefreshAtRef,
    listPollMs,
    loadConversations,
    loadMessages,
    loadMessagesRef,
    logChatDebugRef,
    messagesLoadingRef,
    messagesRef,
    sidebarSearchActive,
    shouldPollActiveThreadIncrementally,
    threadPollMs,
  });

  useChatAiStatusPolling({
    activeConversationId,
    activeConversationKind: activeConversation?.kind,
    activeThreadTransportState,
    aiStatus: activeAiStatus,
    canUseAiChat,
    intervalMs: socketStatus === 'connected' ? CHAT_AI_ACTIVE_POLL_WS_CONNECTED_MS : CHAT_AI_ACTIVE_POLL_MS,
    mergeAiStatusPayload,
    setAiStatusByConversation,
    shouldPollActiveAiThread,
    socketStatus,
  });

  useChatSocketControllerEvents({
    activeConversation,
    activeConversationIdRef,
    aiRunStartedAtByConversationRef,
    applyMessageReadDelta,
    buildActiveThreadPollLoadOptions,
    conversationsLoadingRef,
    hasPendingInitialAnchorForConversation,
    hasPersistedThreadMessageEquivalent,
    lastConversationsLoadAtRef,
    latestActiveThreadSocketMessageRef,
    loadConversations,
    loadMessages,
    loadMessagesRef,
    logChatDebug,
    logChatDebugRef,
    markConversationReadLiveRef,
    markSocketActivity,
    mergeAiStatusPayload,
    mergeMessageIntoThread,
    messagesLoadingRef,
    messagesRef,
    onConversationRemoved,
    promoteConversationToTop,
    queueAutoScroll,
    setAiStatusByConversation,
    setMessages,
    setSocketStatus,
    setTypingUsers,
    setViewerLastReadAt,
    setViewerLastReadMessageId,
    shouldSkipActiveThreadRevalidate,
    skippedInitialSnapshotRefreshRef,
    skippedInitialSocketRefreshRef,
    socketStatusRef,
    syncConversationPreview,
    threadNearBottomRef,
    typingParticipantsTimeoutsRef,
    updatePresenceInCollections,
    upsertConversation,
    userId,
  });
}
