import useChatComposerSending from '../../components/chat/useChatComposerSending';
import useChatComposerUiController from './useChatComposerUiController';
import useChatComposerInteractionController from './useChatComposerInteractionController';
import { loadChatDialogsModule } from './useChatDialogsController';
import useChatUploadsController from './useChatUploadsController';
import { readSelectedDatabaseId } from './chatSessionStorage';

export default function useChatPageComposerStack({
  activeConversation,
  activeConversationId,
  activeConversationIdRef,
  applyOutgoingThreadMessage,
  buildReplyPreview,
  cancelPendingInitialAnchor,
  composerRef,
  createOptimisticFileMessage,
  createOptimisticTextMessage,
  draftWriteTimeoutRef,
  editingMessage,
  fileInputRef,
  flushDraftToStorage,
  focusComposer,
  isMobile,
  latestMessageTextRef,
  logChatDebug,
  mediaFileInputRef,
  mergeMessageIntoThread,
  messageText,
  notifyApiError,
  notifyWarning,
  patchThreadMessage,
  removeThreadMessage,
  replyMessage,
  revokeObjectUrls,
  setComposerMenuAnchor,
  setEditingMessage,
  setEmojiAnchorEl,
  setMessageText,
  setOptimisticAiQueuedStatus,
  setReplyMessage,
  setSocketStatus,
  setThreadMenuAnchor,
  socketStatusRef,
  syncComposerSelection,
  userId,
  emojiAnchorEl,
}) {
  const { handleComposerSend, sendMessage } = useChatComposerSending({
    activeConversation,
    activeConversationId,
    activeConversationIdRef,
    applyOutgoingThreadMessage,
    buildReplyPreview,
    cancelPendingInitialAnchor,
    createOptimisticTextMessage,
    draftWriteTimeoutRef,
    editingMessage,
    flushDraftToStorage,
    focusComposer,
    latestMessageTextRef,
    logChatDebug,
    mergeMessageIntoThread,
    messageText,
    notifyApiError,
    readSelectedDatabaseId,
    removeThreadMessage,
    replyMessage,
    setEditingMessage,
    setMessageText,
    setOptimisticAiQueuedStatus,
    setReplyMessage,
    setSocketStatus,
    socketStatusRef,
    userId,
  });

  const uploads = useChatUploadsController({
    activeConversation,
    activeConversationId,
    applyOutgoingThreadMessage,
    buildReplyPreview,
    cancelPendingInitialAnchor,
    createOptimisticFileMessage,
    fileInputRef,
    loadChatDialogsModule,
    logChatDebug,
    mediaFileInputRef,
    notifyApiError,
    notifyWarning,
    patchThreadMessage,
    removeThreadMessage,
    replyMessage,
    revokeObjectUrls,
    setComposerMenuAnchor,
    setEmojiAnchorEl,
    setOptimisticAiQueuedStatus,
    setReplyMessage,
    setThreadMenuAnchor,
  });

  const composerUi = useChatComposerUiController({
    composerRef,
    emojiAnchorEl,
    focusComposer,
    handleComposerSend,
    isMobile,
    loadChatDialogsModule,
    queueSelectedFiles: uploads.queueSelectedFiles,
    setComposerMenuAnchor,
    setEmojiAnchorEl,
    setMessageText,
    setThreadMenuAnchor,
    syncComposerSelection,
  });

  const composerInteraction = useChatComposerInteractionController({
    focusComposer,
    handleComposerSend,
    setEditingMessage,
    setMessageText,
    setReplyMessage,
  });

  return {
    handleComposerSend,
    sendMessage,
    ...uploads,
    ...composerUi,
    ...composerInteraction,
  };
}
