import { useCallback, useMemo } from 'react';

import buildChatPageDialogsLayerProps from './buildChatPageDialogsLayerProps';

export default function useChatPageDialogsLayerProps(source) {
  const {
  theme,
  ui,
  activeConversation,
  activeConversationId,
  currentUser,
  threadMenuAnchor,
  setThreadMenuAnchor,
  isMobile,
  infoOpen,
  showContextPanel,
  handleOpenInfo,
  messageMenuAnchor,
  messageMenuMessage,
  closeMessageMenu,
  handleToggleReaction,
  handleReplyFromMessageMenu,
  handleCopyMessage,
  handleTogglePinMessageFromMenu,
  pinnedMessage,
  handleCopyMessageLink,
  forwardHookMessageFromMenu,
  handleReportMessageFromMenu,
  handleDeleteMessageFromMenu,
  handleEditFromMessageMenu,
  handleSelectMessageFromMenu,
  handleOpenReadsFromMessageMenu,
  handleOpenAttachmentFromMessageMenu,
  handleOpenTaskFromMessageMenu,
  messages,
  composerMenuAnchor,
  setComposerMenuAnchor,
  openSearchDialog,
  openShareDialog,
  openFilePicker,
  openMediaPicker,
  emojiPickerOpen,
  emojiAnchorEl,
  handleCloseEmojiPicker,
  insertEmojiAtSelection,
  fileInputRef,
  mediaFileInputRef,
  handleSelectFiles,
  fileDialogOpen,
  closeFileDialog,
  selectedFiles,
  fileCaption,
  setFileCaption,
  preparingFiles,
  sendingFiles,
  fileUploadProgress,
  selectedFilesSummary,
  sendFiles,
  removeSelectedFile,
  clearSelectedFiles,
  groupOpen,
  closeGroupDialog,
  groupTitle,
  setGroupTitle,
  groupSearch,
  setGroupSearch,
  groupUsers,
  groupUsersLoading,
  groupSelectedUsers,
  groupMemberIds,
  addGroupMember,
  removeGroupMember,
  creatingConversation,
  groupCreateDisabled,
  createGroup,
  shareOpen,
  resetShareDialog,
  taskSearch,
  setTaskSearch,
  shareableTasks,
  shareableLoading,
  sharingTaskId,
  shareTaskFromHook,
  forwardOpen,
  closeForwardDialog,
  forwardMessages,
  forwardConversationQuery,
  setForwardConversationQuery,
  forwardTargets,
  forwardingConversationId,
  forwardHookMessageToConversation,
  openMediaViewer,
  attachmentPreview,
  closeAttachmentPreview,
  documentPreview,
  closeDocumentPreview,
  handleDownloadDocumentPreview,
  handleDownloadDocumentPreviewPdf,
  messageReadsOpen,
  setMessageReadsOpen,
  messageReadsMessage,
  messageReadsLoading,
  messageReadsItems,
  closeMobileInfoView,
  conversationMetaSubtitle,
  settingsUpdating,
  updateConversationSettings,
  requestConversationRemoval,
  handleAddGroupMembers,
  handleRemoveGroupMember,
  handleUpdateGroupMemberRole,
  handleTransferGroupOwnership,
  handleLeaveGroup,
  handleUpdateGroupProfile,
  openTaskFromChat,
  searchOpen,
  closeSearchDialog,
  messageSearch,
  setMessageSearch,
  messageSearchResults,
  messageSearchLoading,
  messageSearchHasMore,
  loadMoreSearchResults,
  openSearchResult,
  } = source;
  const onCloseThreadMenu = useCallback(() => setThreadMenuAnchor(null), [setThreadMenuAnchor]);
  const onCloseComposerMenu = useCallback(() => setComposerMenuAnchor(null), [setComposerMenuAnchor]);
  const onCloseMessageReads = useCallback(() => setMessageReadsOpen(false), [setMessageReadsOpen]);
  const onToggleReactionFromMenu = useCallback(
    (msg, emoji) => msg?.id && handleToggleReaction(msg.id, emoji),
    [handleToggleReaction],
  );
  const threadInfoOpen = isMobile ? infoOpen : showContextPanel;
  const messageMenuPinned = String(messageMenuMessage?.id || '').trim() === String(pinnedMessage?.id || '').trim();
  const infoPanelOpen = isMobile && infoOpen;
  const forwardSelectionCount = forwardMessages.length;

  return useMemo(
    () => buildChatPageDialogsLayerProps({
      theme,
      ui,
      activeConversation,
      activeConversationId,
      currentUser,
      threadMenuAnchor,
      onCloseThreadMenu,
      threadInfoOpen,
      onOpenInfo: handleOpenInfo,
      messageMenuAnchor,
      messageMenuMessage,
      onCloseMessageMenu: closeMessageMenu,
      onToggleReactionFromMenu,
      onReplyFromMessageMenu: handleReplyFromMessageMenu,
      onCopyMessage: handleCopyMessage,
      onTogglePinMessageFromMenu: handleTogglePinMessageFromMenu,
      messageMenuPinned,
      onCopyMessageLink: handleCopyMessageLink,
      onForwardMessageFromMenu: forwardHookMessageFromMenu,
      onReportMessageFromMenu: handleReportMessageFromMenu,
      onDeleteMessageFromMenu: handleDeleteMessageFromMenu,
      onEditMessageFromMenu: handleEditFromMessageMenu,
      onSelectMessageFromMenu: handleSelectMessageFromMenu,
      onOpenReadsFromMessageMenu: handleOpenReadsFromMessageMenu,
      onOpenAttachmentFromMessageMenu: handleOpenAttachmentFromMessageMenu,
      onOpenTaskFromMessageMenu: handleOpenTaskFromMessageMenu,
      messages,
      composerMenuAnchor,
      onCloseComposerMenu,
      onOpenSearch: openSearchDialog,
      onOpenShare: openShareDialog,
      onOpenFilePicker: openFilePicker,
      onOpenMediaPicker: openMediaPicker,
      emojiPickerOpen,
      emojiAnchorEl,
      onCloseEmojiPicker: handleCloseEmojiPicker,
      onInsertEmoji: insertEmojiAtSelection,
      fileInputRef,
      mediaFileInputRef,
      onSelectFiles: handleSelectFiles,
      fileDialogOpen,
      onCloseFileDialog: closeFileDialog,
      selectedFiles,
      fileCaption,
      onFileCaptionChange: setFileCaption,
      preparingFiles,
      sendingFiles,
      fileUploadProgress,
      fileSummary: selectedFilesSummary,
      onSendFiles: sendFiles,
      onRemoveSelectedFile: removeSelectedFile,
      onClearSelectedFiles: clearSelectedFiles,
      groupOpen,
      onCloseGroup: closeGroupDialog,
      groupTitle,
      onGroupTitleChange: setGroupTitle,
      groupSearch,
      onGroupSearchChange: setGroupSearch,
      groupUsers,
      groupUsersLoading,
      groupSelectedUsers,
      groupMemberIds,
      onAddGroupMember: addGroupMember,
      onRemoveGroupMember: removeGroupMember,
      creatingConversation,
      groupCreateDisabled,
      onCreateGroup: createGroup,
      shareOpen,
      onCloseShare: resetShareDialog,
      taskSearch,
      onTaskSearchChange: setTaskSearch,
      shareableTasks,
      shareableLoading,
      sharingTaskId,
      onShareTask: shareTaskFromHook,
      forwardOpen,
      onCloseForward: closeForwardDialog,
      forwardSelectionCount,
      forwardConversationQuery,
      onForwardConversationQueryChange: setForwardConversationQuery,
      forwardTargets,
      forwardTargetsLoading: false,
      forwardingConversationId,
      onForwardMessageToConversation: forwardHookMessageToConversation,
      onOpenAttachmentPreview: openMediaViewer,
      attachmentPreview,
      onCloseAttachmentPreview: closeAttachmentPreview,
      documentPreview,
      onCloseDocumentPreview: closeDocumentPreview,
      onDownloadDocumentPreview: handleDownloadDocumentPreview,
      onDownloadDocumentPreviewPdf: handleDownloadDocumentPreviewPdf,
      messageReadsOpen,
      onCloseMessageReads,
      messageReadsMessage,
      messageReadsLoading,
      messageReadsItems,
      infoOpen: infoPanelOpen,
      onCloseInfo: closeMobileInfoView,
      conversationHeaderSubtitle: conversationMetaSubtitle,
      settingsUpdating,
      onUpdateConversationSettings: updateConversationSettings,
      onRequestDeleteConversation: requestConversationRemoval,
      onAddGroupMembers: handleAddGroupMembers,
      onRemoveGroupParticipant: handleRemoveGroupMember,
      onUpdateGroupMemberRole: handleUpdateGroupMemberRole,
      onTransferGroupOwnership: handleTransferGroupOwnership,
      onLeaveGroup: handleLeaveGroup,
      onUpdateGroupProfile: handleUpdateGroupProfile,
      onOpenTask: openTaskFromChat,
      searchOpen,
      onCloseSearch: closeSearchDialog,
      messageSearch,
      onMessageSearchChange: setMessageSearch,
      messageSearchResults,
      messageSearchLoading,
      messageSearchHasMore,
      onLoadMoreSearchResults: loadMoreSearchResults,
      onOpenSearchResult: openSearchResult,
    }),
    [
      addGroupMember,
      attachmentPreview,
      closeAttachmentPreview,
      closeForwardDialog,
      closeGroupDialog,
      closeMessageMenu,
      closeMobileInfoView,
      closeSearchDialog,
      composerMenuAnchor,
      conversationMetaSubtitle,
      createGroup,
      creatingConversation,
      currentUser,
      documentPreview,
      emojiAnchorEl,
      emojiPickerOpen,
      fileCaption,
      fileDialogOpen,
      fileInputRef,
      fileUploadProgress,
      forwardConversationQuery,
      forwardHookMessageFromMenu,
      forwardHookMessageToConversation,
      forwardMessages,
      forwardOpen,
      forwardSelectionCount,
      forwardTargets,
      forwardingConversationId,
      groupCreateDisabled,
      groupMemberIds,
      groupOpen,
      groupSearch,
      groupSelectedUsers,
      groupTitle,
      groupUsers,
      groupUsersLoading,
      handleAddGroupMembers,
      handleCloseEmojiPicker,
      handleCopyMessage,
      handleCopyMessageLink,
      handleDeleteMessageFromMenu,
      handleDownloadDocumentPreview,
      handleDownloadDocumentPreviewPdf,
      handleEditFromMessageMenu,
      handleLeaveGroup,
      handleOpenAttachmentFromMessageMenu,
      handleOpenInfo,
      handleOpenReadsFromMessageMenu,
      handleOpenTaskFromMessageMenu,
      handleRemoveGroupMember,
      handleReplyFromMessageMenu,
      handleReportMessageFromMenu,
      handleSelectMessageFromMenu,
      handleTogglePinMessageFromMenu,
      handleTransferGroupOwnership,
      handleUpdateGroupMemberRole,
      handleUpdateGroupProfile,
      infoPanelOpen,
      insertEmojiAtSelection,
      loadMoreSearchResults,
      mediaFileInputRef,
      messageMenuAnchor,
      messageMenuMessage,
      messageMenuPinned,
      messageReadsItems,
      messageReadsLoading,
      messageReadsMessage,
      messageReadsOpen,
      messageSearch,
      messageSearchHasMore,
      messageSearchLoading,
      messageSearchResults,
      messages,
      onCloseComposerMenu,
      onCloseMessageReads,
      onCloseThreadMenu,
      onToggleReactionFromMenu,
      openFilePicker,
      openMediaPicker,
      openMediaViewer,
      openSearchDialog,
      openSearchResult,
      openShareDialog,
      openTaskFromChat,
      preparingFiles,
      removeGroupMember,
      removeSelectedFile,
      requestConversationRemoval,
      resetShareDialog,
      searchOpen,
      selectedFiles,
      selectedFilesSummary,
      sendFiles,
      sendingFiles,
      settingsUpdating,
      shareableLoading,
      shareableTasks,
      shareOpen,
      shareTaskFromHook,
      sharingTaskId,
      taskSearch,
      theme,
      threadInfoOpen,
      threadMenuAnchor,
      ui,
      updateConversationSettings,
      activeConversation,
      activeConversationId,
      clearSelectedFiles,
      closeFileDialog,
      handleSelectFiles,
      setFileCaption,
      setForwardConversationQuery,
      setGroupSearch,
      setGroupTitle,
      setMessageSearch,
      setTaskSearch,
    ],
  );
}
