import { describe, expect, it, vi } from 'vitest';
import { renderHook } from '@testing-library/react';

import useChatPageDialogsLayerProps from './useChatPageDialogsLayerProps';

function buildMinimalArgs(overrides = {}) {
  const noop = vi.fn();
  return {
    theme: {},
    ui: {},
    activeConversation: { id: 'c1' },
    activeConversationId: 'c1',
    currentUser: { id: 'u1' },
    threadMenuAnchor: null,
    setThreadMenuAnchor: noop,
    isMobile: false,
    infoOpen: false,
    showContextPanel: false,
    handleOpenInfo: noop,
    messageMenuAnchor: null,
    messageMenuMessage: null,
    closeMessageMenu: noop,
    handleToggleReaction: noop,
    handleReplyFromMessageMenu: noop,
    handleCopyMessage: noop,
    handleTogglePinMessageFromMenu: noop,
    pinnedMessage: null,
    handleCopyMessageLink: noop,
    forwardHookMessageFromMenu: noop,
    handleReportMessageFromMenu: noop,
    handleDeleteMessageFromMenu: noop,
    handleEditFromMessageMenu: noop,
    handleSelectMessageFromMenu: noop,
    handleOpenReadsFromMessageMenu: noop,
    handleOpenAttachmentFromMessageMenu: noop,
    handleOpenTaskFromMessageMenu: noop,
    messages: [],
    composerMenuAnchor: null,
    setComposerMenuAnchor: noop,
    openSearchDialog: noop,
    openShareDialog: noop,
    openFilePicker: noop,
    openMediaPicker: noop,
    emojiPickerOpen: false,
    emojiAnchorEl: null,
    handleCloseEmojiPicker: noop,
    insertEmojiAtSelection: noop,
    fileInputRef: { current: null },
    mediaFileInputRef: { current: null },
    handleSelectFiles: noop,
    fileDialogOpen: false,
    closeFileDialog: noop,
    selectedFiles: [],
    fileCaption: '',
    setFileCaption: noop,
    preparingFiles: false,
    sendingFiles: false,
    fileUploadProgress: 0,
    selectedFilesSummary: null,
    sendFiles: noop,
    removeSelectedFile: noop,
    clearSelectedFiles: noop,
    groupOpen: false,
    closeGroupDialog: noop,
    groupTitle: '',
    setGroupTitle: noop,
    groupSearch: '',
    setGroupSearch: noop,
    groupUsers: [],
    groupUsersLoading: false,
    groupSelectedUsers: [],
    groupMemberIds: [],
    addGroupMember: noop,
    removeGroupMember: noop,
    creatingConversation: false,
    groupCreateDisabled: true,
    createGroup: noop,
    shareOpen: false,
    resetShareDialog: noop,
    taskSearch: '',
    setTaskSearch: noop,
    shareableTasks: [],
    shareableLoading: false,
    sharingTaskId: '',
    shareTaskFromHook: noop,
    forwardOpen: false,
    closeForwardDialog: noop,
    forwardMessages: [],
    forwardConversationQuery: '',
    setForwardConversationQuery: noop,
    forwardTargets: [],
    forwardingConversationId: '',
    forwardHookMessageToConversation: noop,
    openMediaViewer: noop,
    attachmentPreview: null,
    closeAttachmentPreview: noop,
    documentPreview: null,
    closeDocumentPreview: noop,
    handleDownloadDocumentPreview: noop,
    handleDownloadDocumentPreviewPdf: noop,
    messageReadsOpen: false,
    setMessageReadsOpen: noop,
    messageReadsMessage: null,
    messageReadsLoading: false,
    messageReadsItems: [],
    closeMobileInfoView: noop,
    conversationMetaSubtitle: 'subtitle',
    settingsUpdating: false,
    updateConversationSettings: noop,
    requestConversationRemoval: noop,
    handleAddGroupMembers: noop,
    handleRemoveGroupMember: noop,
    handleUpdateGroupMemberRole: noop,
    handleTransferGroupOwnership: noop,
    handleLeaveGroup: noop,
    handleUpdateGroupProfile: noop,
    openTaskFromChat: noop,
    searchOpen: false,
    closeSearchDialog: noop,
    messageSearch: '',
    setMessageSearch: noop,
    messageSearchResults: [],
    messageSearchLoading: false,
    messageSearchHasMore: false,
    loadMoreSearchResults: noop,
    openSearchResult: noop,
    ...overrides,
  };
}

describe('useChatPageDialogsLayerProps', () => {
  it('returns memoized dialog layer props with conversation id', () => {
    const { result } = renderHook(() => useChatPageDialogsLayerProps(buildMinimalArgs()));

    expect(result.current.activeConversationId).toBe('c1');
    expect(result.current.conversationHeaderSubtitle).toBe('subtitle');
    expect(result.current.forwardSelectionCount).toBe(0);
  });

  it('uses mobile info panel open state on phone', () => {
    const { result } = renderHook(() => useChatPageDialogsLayerProps(buildMinimalArgs({
      isMobile: true,
      infoOpen: true,
    })));

    expect(result.current.infoOpen).toBe(true);
  });
});
