import { useCallback, useMemo } from 'react';

import buildChatPageDialogsLayerProps from './buildChatPageDialogsLayerProps';

export default function useChatPageDialogsLayerProps(source) {
  const {
  theme,
  ui,
  activeConversation,
  activeAiBot,
  activeAiStatus,
  handleCreateAiBotConversation,
  handleCreateAiConversation,
  openingAiBotId,
  activeConversationId,
  currentUser,
  threadMenuAnchor,
  setThreadMenuAnchor,
  isMobile,
  infoOpen,
  showContextPanel,
  handleOpenInfo,
  messageMenuAnchor,
  messageMenuMessage,
  closeMessageMenu,
  handleToggleReaction,
  handleReplyFromMessageMenu,
  handleCopyMessage,
  handleTogglePinMessageFromMenu,
  pinnedMessage,
  handleCopyMessageLink,
  forwardHookMessageFromMenu,
  handleReportMessageFromMenu,
  handleDeleteMessageFromMenu,
  handleEditFromMessageMenu,
  handleSelectMessageFromMenu,
  handleOpenReadsFromMessageMenu,
  handlePollVote,
  handlePollClose,
  handleOpenAttachmentFromMessageMenu,
  handleOpenTaskFromMessageMenu,
  messages,
  composerMenuAnchor,
  setComposerMenuAnchor,
  openSearchDialog,
  openShareDialog,
  openFilePicker,
  openMediaPicker,
  emojiPickerOpen,
  emojiAnchorEl,
  handleCloseEmojiPicker,
  insertEmojiAtSelection,
  handleSendSticker,
  fileInputRef,
  mediaFileInputRef,
  handleSelectFiles,
  fileDialogOpen,
  closeFileDialog,
  selectedFiles,
  selectedImageEdits,
  fileCaption,
  setFileCaption,
  sendMediaAsFiles,
  changeSendMediaAsFiles,
  preparingFiles,
  sendingFiles,
  fileUploadProgress,
  selectedFilesSummary,
  sendFiles,
  removeSelectedFile,
  clearSelectedFiles,
  applySelectedImageEdit,
  resetSelectedImageEdit,
  structuredDialog,
  openPollDialog,
  openContactDialog,
  sendLocationMessage,
  closeStructuredDialog,
  sendPollMessage,
  sendContactMessage,
  confirmLocationMessage,
  locationDraft,
  locationSending,
  shareOpen,
  resetShareDialog,
  taskSearch,
  setTaskSearch,
  shareableTasks,
  shareableLoading,
  sharingTaskId,
  shareTaskFromHook,
  forwardOpen,
  closeForwardDialog,
  forwardMessages,
  forwardConversationQuery,
  setForwardConversationQuery,
  forwardTargets,
  forwardingConversationId,
  forwardHookMessageToConversation,
  openMediaViewer,
  attachmentPreview,
  closeAttachmentPreview,
  documentPreview,
  closeDocumentPreview,
  handleDownloadDocumentPreview,
  handleDownloadDocumentPreviewPdf,
  messageReadsOpen,
  setMessageReadsOpen,
  messageReadsMessage,
  messageReadsLoading,
  messageReadsItems,
  closeMobileInfoView,
  conversationMetaSubtitle,
  settingsUpdating,
  updateConversationSettings,
  requestConversationRemoval,
  handleAddGroupMembers,
  handleRemoveGroupMember,
  handleUpdateGroupMemberRole,
  handleTransferGroupOwnership,
  handleLeaveGroup,
  handleUpdateGroupProfile,
  openTaskFromChat,
  searchOpen,
  closeSearchDialog,
  messageSearch,
  setMessageSearch,
  messageSearchResults,
  messageSearchLoading,
  messageSearchHasMore,
  loadMoreSearchResults,
  openSearchResult,
  } = source;
  const onCloseThreadMenu = useCallback(() => setThreadMenuAnchor(null), [setThreadMenuAnchor]);
  const onCloseComposerMenu = useCallback(() => setComposerMenuAnchor(null), [setComposerMenuAnchor]);
  const onCloseMessageReads = useCallback(() => setMessageReadsOpen(false), [setMessageReadsOpen]);
  const onToggleReactionFromMenu = useCallback(
    (msg, emoji) => msg?.id && handleToggleReaction(msg.id, emoji),
    [handleToggleReaction],
  );
  // R50: «Остановить опрос» и «Отменить голос» — из меню сообщения; те же вызовы, что раньше шли из карточки.
  // Повторный голос за тот же вариант снимает голос (backend).
  const onStopPollFromMessageMenu = useCallback(
    (msg) => msg?.id && handlePollClose?.(msg.id),
    [handlePollClose],
  );
  const onCancelPollVoteFromMessageMenu = useCallback(
    (msg, optionIndex) => msg?.id && handlePollVote?.(msg.id, optionIndex),
    [handlePollVote],
  );
  const threadInfoOpen = isMobile ? infoOpen : showContextPanel;
  const messageMenuPinned = String(messageMenuMessage?.id || '').trim() === String(pinnedMessage?.id || '').trim();
  const infoPanelOpen = isMobile && infoOpen;
  const forwardSelectionCount = forwardMessages.length;

  return useMemo(
    () => buildChatPageDialogsLayerProps({
      theme,
      ui,
      activeConversation,
      activeAiBot,
      activeAiStatus,
      handleCreateAiBotConversation,
      handleCreateAiConversation,
      openingAiBotId,
      activeConversationId,
      currentUser,
      threadMenuAnchor,
      onCloseThreadMenu,
      threadInfoOpen,
      onOpenInfo: handleOpenInfo,
      messageMenuAnchor,
      messageMenuMessage,
      onCloseMessageMenu: closeMessageMenu,
      onToggleReactionFromMenu,
      onReplyFromMessageMenu: handleReplyFromMessageMenu,
      onCopyMessage: handleCopyMessage,
      onTogglePinMessageFromMenu: handleTogglePinMessageFromMenu,
      messageMenuPinned,
      onCopyMessageLink: handleCopyMessageLink,
      onForwardMessageFromMenu: forwardHookMessageFromMenu,
      onReportMessageFromMenu: handleReportMessageFromMenu,
      onDeleteMessageFromMenu: handleDeleteMessageFromMenu,
      onEditMessageFromMenu: handleEditFromMessageMenu,
      onSelectMessageFromMenu: handleSelectMessageFromMenu,
      onOpenReadsFromMessageMenu: handleOpenReadsFromMessageMenu,
      onStopPollFromMessageMenu,
      onCancelPollVoteFromMessageMenu,
      onOpenAttachmentFromMessageMenu: handleOpenAttachmentFromMessageMenu,
      onOpenTaskFromMessageMenu: handleOpenTaskFromMessageMenu,
      messages,
      composerMenuAnchor,
      onCloseComposerMenu,
      onOpenSearch: openSearchDialog,
      onOpenShare: openShareDialog,
      onOpenFilePicker: openFilePicker,
      onOpenMediaPicker: openMediaPicker,
      emojiPickerOpen,
      emojiAnchorEl,
      onCloseEmojiPicker: handleCloseEmojiPicker,
      onInsertEmoji: insertEmojiAtSelection,
      onSendSticker: handleSendSticker,
      fileInputRef,
      mediaFileInputRef,
      onSelectFiles: handleSelectFiles,
      fileDialogOpen,
      onCloseFileDialog: closeFileDialog,
      selectedFiles,
      imageEdits: selectedImageEdits,
      onApplyImageEdit: applySelectedImageEdit,
      onResetImageEdit: resetSelectedImageEdit,
      fileCaption,
      onFileCaptionChange: setFileCaption,
      sendMediaAsFiles,
      onSendMediaAsFilesChange: changeSendMediaAsFiles,
      preparingFiles,
      sendingFiles,
      fileUploadProgress,
      fileSummary: selectedFilesSummary,
      onSendFiles: sendFiles,
      onRemoveSelectedFile: removeSelectedFile,
      onClearSelectedFiles: clearSelectedFiles,
      structuredDialog,
      onOpenPollDialog: openPollDialog,
      onOpenContactDialog: openContactDialog,
      onSendLocation: sendLocationMessage,
      locationSending,
      onCloseStructuredDialog: closeStructuredDialog,
      onSendPoll: sendPollMessage,
      onSendContact: sendContactMessage,
      onConfirmLocation: confirmLocationMessage,
      locationDraft,
      shareOpen,
      onCloseShare: resetShareDialog,
      taskSearch,
      onTaskSearchChange: setTaskSearch,
      shareableTasks,
      shareableLoading,
      sharingTaskId,
      onShareTask: shareTaskFromHook,
      forwardOpen,
      onCloseForward: closeForwardDialog,
      forwardSelectionCount,
      forwardConversationQuery,
      onForwardConversationQueryChange: setForwardConversationQuery,
      forwardTargets,
      forwardTargetsLoading: false,
      forwardingConversationId,
      onForwardMessageToConversation: forwardHookMessageToConversation,
      onOpenAttachmentPreview: openMediaViewer,
      attachmentPreview,
      onCloseAttachmentPreview: closeAttachmentPreview,
      documentPreview,
      onCloseDocumentPreview: closeDocumentPreview,
      onDownloadDocumentPreview: handleDownloadDocumentPreview,
      onDownloadDocumentPreviewPdf: handleDownloadDocumentPreviewPdf,
      messageReadsOpen,
      onCloseMessageReads,
      messageReadsMessage,
      messageReadsLoading,
      messageReadsItems,
      infoOpen: infoPanelOpen,
      onCloseInfo: closeMobileInfoView,
      conversationHeaderSubtitle: conversationMetaSubtitle,
      settingsUpdating,
      onUpdateConversationSettings: updateConversationSettings,
      onRequestDeleteConversation: requestConversationRemoval,
      onAddGroupMembers: handleAddGroupMembers,
      onRemoveGroupParticipant: handleRemoveGroupMember,
      onUpdateGroupMemberRole: handleUpdateGroupMemberRole,
      onTransferGroupOwnership: handleTransferGroupOwnership,
      onLeaveGroup: handleLeaveGroup,
      onUpdateGroupProfile: handleUpdateGroupProfile,
      onOpenTask: openTaskFromChat,
      searchOpen,
      onCloseSearch: closeSearchDialog,
      messageSearch,
      onMessageSearchChange: setMessageSearch,
      messageSearchResults,
      messageSearchLoading,
      messageSearchHasMore,
      onLoadMoreSearchResults: loadMoreSearchResults,
      onOpenSearchResult: openSearchResult,
    }),
    [
      applySelectedImageEdit,
      attachmentPreview,
      closeAttachmentPreview,
      closeForwardDialog,
      closeMessageMenu,
      closeMobileInfoView,
      closeSearchDialog,
      composerMenuAnchor,
      conversationMetaSubtitle,
      currentUser,
      documentPreview,
      emojiAnchorEl,
      emojiPickerOpen,
      fileCaption,
      fileDialogOpen,
      fileInputRef,
      fileUploadProgress,
      forwardConversationQuery,
      forwardHookMessageFromMenu,
      forwardHookMessageToConversation,
      forwardMessages,
      forwardOpen,
      forwardSelectionCount,
      forwardTargets,
      forwardingConversationId,
      handleAddGroupMembers,
      handleCloseEmojiPicker,
      handleCopyMessage,
      handleCopyMessageLink,
      handleDeleteMessageFromMenu,
      handleDownloadDocumentPreview,
      handleDownloadDocumentPreviewPdf,
      handleEditFromMessageMenu,
      handleLeaveGroup,
      handleOpenAttachmentFromMessageMenu,
      handleOpenInfo,
      handleOpenReadsFromMessageMenu,
      onStopPollFromMessageMenu,
      onCancelPollVoteFromMessageMenu,
      handleOpenTaskFromMessageMenu,
      handleRemoveGroupMember,
      handleReplyFromMessageMenu,
      handleReportMessageFromMenu,
      handleSelectMessageFromMenu,
      handleSendSticker,
      handleTogglePinMessageFromMenu,
      handleTransferGroupOwnership,
      handleUpdateGroupMemberRole,
      handleUpdateGroupProfile,
      infoPanelOpen,
      insertEmojiAtSelection,
      loadMoreSearchResults,
      mediaFileInputRef,
      messageMenuAnchor,
      messageMenuMessage,
      messageMenuPinned,
      messageReadsItems,
      messageReadsLoading,
      messageReadsMessage,
      messageReadsOpen,
      messageSearch,
      messageSearchHasMore,
      messageSearchLoading,
      messageSearchResults,
      messages,
      onCloseComposerMenu,
      onCloseMessageReads,
      onCloseThreadMenu,
      onToggleReactionFromMenu,
      openFilePicker,
      openMediaPicker,
      openMediaViewer,
      openSearchDialog,
      openSearchResult,
      openShareDialog,
      openTaskFromChat,
      preparingFiles,
      removeSelectedFile,
      requestConversationRemoval,
      closeStructuredDialog,
      confirmLocationMessage,
      locationDraft,
      locationSending,
      openContactDialog,
      openPollDialog,
      sendContactMessage,
      sendLocationMessage,
      sendPollMessage,
      structuredDialog,
      resetShareDialog,
      resetSelectedImageEdit,
      searchOpen,
      selectedFiles,
      selectedImageEdits,
      selectedFilesSummary,
      sendMediaAsFiles,
      sendFiles,
      sendingFiles,
      settingsUpdating,
      shareableLoading,
      shareableTasks,
      shareOpen,
      shareTaskFromHook,
      sharingTaskId,
      taskSearch,
      theme,
      threadInfoOpen,
      threadMenuAnchor,
      ui,
      updateConversationSettings,
      activeConversation,
      activeAiBot,
      activeAiStatus,
      handleCreateAiBotConversation,
      handleCreateAiConversation,
      openingAiBotId,
      activeConversationId,
      clearSelectedFiles,
      changeSendMediaAsFiles,
      closeFileDialog,
      handleSelectFiles,
      setFileCaption,
      setForwardConversationQuery,
      setMessageSearch,
      setTaskSearch,
    ],
  );
}
