import { useMemo } from 'react';

import ChatThread from '../../components/chat/ChatThread';
import useChatComposerTextBridge from '../../components/chat/useChatComposerTextBridge';
import ChatPageRightPanelContent from './ChatPageRightPanelContent';
import buildChatPagePanesBags from './buildChatPagePanesBags';

export default function useChatThreadSection(ctx) {
  const { shell, thread, rightPanel } = buildChatPagePanesBags(ctx);
  const { theme, ui, isMobile, isPhone } = shell;
  const {
    activeConversation,
    navigate,
    threadWallpaperSx,
    messages,
    messagesLoading,
    effectiveLastReadMessageId,
    showOlderHistoryControl,
    loadingOlder,
    prependScrollRestoreRef,
    loadOlderMessages,
    threadScrollRef,
    threadContentRef,
    handleThreadScroll,
    bottomRef,
    openMobileInboxView,
    handleOpenInfo,
    openTaskFromChat,
    openSearchDialog,
    handleOpenMenu,
    openMessageReads,
    openMediaViewer,
    handleReplyMessage,
    openMessageMenu,
    confirmAiAction,
    cancelAiAction,
    editAiAction,
    selectedVisibleMessageIds,
    selectedMessageCount,
    canCopySelectedMessages,
    toggleMessageSelection,
    startMessageSelection,
    clearSelectedMessages,
    selectedReplyToSelectedMessage,
    selectedCopySelectedMessages,
    selectedOpenForwardSelectedMessages,
    handleOpenComposerMenu,
    composerRef,
    messageText,
    setMessageText,
    handleComposerKeyDown,
    syncComposerSelection,
    handleOpenEmojiPicker,
    handleCloseEmojiPicker,
    handleComposerFocusChange,
    handleComposerSend,
    handleComposerPaste,
    handleComposerDrop,
    handleComposerDragOver,
    handleComposerDragLeave,
    mentionCandidates,
    searchMentionPeople,
    fileDragActive,
    showJumpToLatest,
    jumpToLatest,
    replyMessage,
    clearReplyMessage,
    editingMessage,
    clearEditingMessage,
    aiTypingStatus,
    activeAiStatus,
    pinnedMessage,
    handleOpenPinnedMessage,
    handleUnpinPinnedMessage,
    highlightedMessageId,
    conversationMetaSubtitle,
    aiAwareTypingLine,
    renderDesktopRightPanel,
    selectedFiles,
    fileCaption,
    openFilePicker,
    clearSelectedFiles,
    preparingFiles,
    sendingFiles,
    fileUploadProgress,
    selectedFilesSummary,
    getReadTargetRef,
    handleToggleReaction,
    scrollToMessage,
    emojiPickerOpen,
    insertEmojiAtSelection,
    handleSendGif,
    voiceRecording,
    voiceRecordingDuration,
    voiceRecordingLevelRef,
    startVoiceRecording,
    stopVoiceRecording,
    cancelVoiceRecording,
    bindPinnedScroll,
    activeConversationId,
  } = thread;
  const {
    showTaskPanel,
    showContextPanel,
    taskPanelTaskId,
    closeTaskPanel,
    openTaskInTasks,
    handleTaskPanelUpdated,
    setContextPanelOpen,
    openShareDialog,
    handleAddGroupMembers,
    handleRemoveGroupMember,
    handleUpdateGroupMemberRole,
    handleTransferGroupOwnership,
    handleLeaveGroup,
    handleUpdateGroupProfile,
    settingsUpdating,
    socketStatus,
    user,
    updateConversationSettings,
  } = rightPanel;

  const composerTextBridge = useChatComposerTextBridge({
    messageText,
    setMessageText,
    onComposerKeyDown: handleComposerKeyDown,
    onComposerSelectionSync: syncComposerSelection,
  });

  const threadPane = useMemo(
    () => (
      <ChatThread
        theme={theme}
        ui={ui}
        isMobile={isMobile}
        compactMobile={isPhone}
        mobileInteractionsEnabled={isMobile}
        activeConversation={activeConversation}
        activeConversationId={activeConversationId}
        navigate={navigate}
        threadWallpaperSx={threadWallpaperSx}
        messages={messages}
        messagesLoading={messagesLoading}
        effectiveLastReadMessageId={effectiveLastReadMessageId}
        messagesHasMore={showOlderHistoryControl}
        loadingOlder={loadingOlder}
        prependScrollRestoreRef={prependScrollRestoreRef}
        onLoadOlder={loadOlderMessages}
        threadScrollRef={threadScrollRef}
        threadContentRef={threadContentRef}
        onThreadScroll={handleThreadScroll}
        bottomRef={bottomRef}
        onBack={openMobileInboxView}
        onOpenInfo={handleOpenInfo}
        onOpenTask={openTaskFromChat}
        onOpenSearch={openSearchDialog}
        onOpenMenu={handleOpenMenu}
        onOpenReads={openMessageReads}
        onOpenAttachmentPreview={openMediaViewer}
        onReplyMessage={handleReplyMessage}
        onOpenMessageMenu={openMessageMenu}
        onConfirmAction={confirmAiAction}
        onCancelAction={cancelAiAction}
        onEditAction={editAiAction}
        selectedMessageIds={selectedVisibleMessageIds}
        selectedMessageCount={selectedMessageCount}
        canReplySelectedMessage={selectedMessageCount === 1}
        canCopySelectedMessages={canCopySelectedMessages}
        onToggleMessageSelection={toggleMessageSelection}
        onStartMessageSelection={startMessageSelection}
        onClearMessageSelection={clearSelectedMessages}
        onReplySelectedMessage={selectedReplyToSelectedMessage}
        onCopySelectedMessages={selectedCopySelectedMessages}
        onForwardSelectedMessages={selectedOpenForwardSelectedMessages}
        onOpenComposerMenu={handleOpenComposerMenu}
        composerRef={composerRef}
        composerTextBridge={composerTextBridge}
        onOpenEmojiPicker={handleOpenEmojiPicker}
        onCloseEmojiPicker={handleCloseEmojiPicker}
        onComposerFocusChange={handleComposerFocusChange}
        onSendMessage={handleComposerSend}
        onComposerPaste={handleComposerPaste}
        onComposerDrop={handleComposerDrop}
        onComposerDragOver={handleComposerDragOver}
        onComposerDragLeave={handleComposerDragLeave}
        mentionCandidates={mentionCandidates}
        onSearchMentionPeople={searchMentionPeople}
        isFileDragActive={fileDragActive}
        showJumpToLatest={showJumpToLatest}
        onJumpToLatest={jumpToLatest}
        replyMessage={replyMessage}
        onClearReply={clearReplyMessage}
        editingMessage={editingMessage}
        onClearEditing={clearEditingMessage}
        aiTypingStatus={aiTypingStatus}
        aiStatus={activeConversation?.kind === 'ai' ? activeAiStatus : null}
        pinnedMessage={pinnedMessage}
        onOpenPinnedMessage={handleOpenPinnedMessage}
        onUnpinPinnedMessage={handleUnpinPinnedMessage}
        highlightedMessageId={highlightedMessageId}
        headerSubtitle={conversationMetaSubtitle}
        typingLine={aiAwareTypingLine}
        contextPanelOpen={renderDesktopRightPanel}
        selectedFiles={selectedFiles}
        fileCaption={fileCaption}
        onOpenFileDialog={openFilePicker}
        onClearSelectedFiles={clearSelectedFiles}
        preparingFiles={preparingFiles}
        sendingFiles={sendingFiles}
        fileUploadProgress={fileUploadProgress}
        selectedFilesSummary={selectedFilesSummary}
        getReadTargetRef={getReadTargetRef}
        onToggleReaction={handleToggleReaction}
        onScrollToMessage={scrollToMessage}
        currentUserId={user?.id}
        mobileEmojiPickerOpen={isMobile && emojiPickerOpen}
        onInsertEmoji={insertEmojiAtSelection}
        onSendSticker={insertEmojiAtSelection}
        onSendGif={handleSendGif}
        voiceRecording={voiceRecording}
        voiceRecordingDuration={voiceRecordingDuration}
        voiceRecordingLevelRef={voiceRecordingLevelRef}
        onStartVoiceRecording={startVoiceRecording}
        onStopVoiceRecording={stopVoiceRecording}
        onCancelVoiceRecording={cancelVoiceRecording}
        onBindPinnedScroll={bindPinnedScroll}
      />
    ),
    [
      activeAiStatus,
      activeConversation,
      activeConversationId,
      aiAwareTypingLine,
      aiTypingStatus,
      bindPinnedScroll,
      bottomRef,
      cancelAiAction,
      cancelVoiceRecording,
      canCopySelectedMessages,
      clearEditingMessage,
      clearReplyMessage,
      clearSelectedFiles,
      clearSelectedMessages,
      composerRef,
      composerTextBridge,
      confirmAiAction,
      conversationMetaSubtitle,
      editAiAction,
      effectiveLastReadMessageId,
      emojiPickerOpen,
      fileCaption,
      fileDragActive,
      fileUploadProgress,
      getReadTargetRef,
      handleComposerDragLeave,
      handleComposerDragOver,
      handleComposerDrop,
      handleComposerFocusChange,
      handleComposerPaste,
      handleComposerSend,
      handleCloseEmojiPicker,
      handleOpenComposerMenu,
      handleOpenEmojiPicker,
      handleOpenInfo,
      handleOpenMenu,
      handleOpenPinnedMessage,
      handleReplyMessage,
      handleSendGif,
      handleThreadScroll,
      handleToggleReaction,
      handleUnpinPinnedMessage,
      highlightedMessageId,
      insertEmojiAtSelection,
      isMobile,
      isPhone,
      jumpToLatest,
      loadOlderMessages,
      loadingOlder,
      mentionCandidates,
      messages,
      messagesLoading,
      navigate,
      openMediaViewer,
      openMessageMenu,
      openMessageReads,
      openMobileInboxView,
      openSearchDialog,
      openTaskFromChat,
      pinnedMessage,
      prependScrollRestoreRef,
      preparingFiles,
      replyMessage,
      renderDesktopRightPanel,
      scrollToMessage,
      searchMentionPeople,
      selectedCopySelectedMessages,
      selectedFiles,
      selectedFilesSummary,
      selectedMessageCount,
      selectedOpenForwardSelectedMessages,
      selectedReplyToSelectedMessage,
      selectedVisibleMessageIds,
      sendingFiles,
      showJumpToLatest,
      showOlderHistoryControl,
      startMessageSelection,
      startVoiceRecording,
      stopVoiceRecording,
      theme,
      threadContentRef,
      threadScrollRef,
      threadWallpaperSx,
      toggleMessageSelection,
      ui,
      user?.id,
      voiceRecording,
      voiceRecordingDuration,
      voiceRecordingLevelRef,
      editingMessage,
    ],
  );

  const desktopRightPanelContent = useMemo(
    () => (
      <ChatPageRightPanelContent
        showTaskPanel={showTaskPanel}
        showContextPanel={showContextPanel}
        taskPanelTaskId={taskPanelTaskId}
        closeTaskPanel={closeTaskPanel}
        openTaskInTasks={openTaskInTasks}
        navigate={navigate}
        handleTaskPanelUpdated={handleTaskPanelUpdated}
        theme={theme}
        ui={ui}
        activeConversation={activeConversation}
        conversationMetaSubtitle={conversationMetaSubtitle}
        socketStatus={socketStatus}
        user={user}
        messages={messages}
        onCloseContextPanel={() => setContextPanelOpen(false)}
        openSearchDialog={openSearchDialog}
        openShareDialog={openShareDialog}
        openFilePicker={openFilePicker}
        updateConversationSettings={updateConversationSettings}
        handleAddGroupMembers={handleAddGroupMembers}
        handleRemoveGroupMember={handleRemoveGroupMember}
        handleUpdateGroupMemberRole={handleUpdateGroupMemberRole}
        handleTransferGroupOwnership={handleTransferGroupOwnership}
        handleLeaveGroup={handleLeaveGroup}
        handleUpdateGroupProfile={handleUpdateGroupProfile}
        settingsUpdating={settingsUpdating}
        openMediaViewer={openMediaViewer}
        openTaskFromChat={openTaskFromChat}
      />
    ),
    [
      activeConversation,
      conversationMetaSubtitle,
      closeTaskPanel,
      handleAddGroupMembers,
      handleLeaveGroup,
      handleRemoveGroupMember,
      handleTaskPanelUpdated,
      handleTransferGroupOwnership,
      handleUpdateGroupMemberRole,
      handleUpdateGroupProfile,
      messages,
      navigate,
      openFilePicker,
      openMediaViewer,
      openSearchDialog,
      openShareDialog,
      openTaskFromChat,
      openTaskInTasks,
      settingsUpdating,
      setContextPanelOpen,
      showContextPanel,
      showTaskPanel,
      socketStatus,
      taskPanelTaskId,
      theme,
      ui,
      updateConversationSettings,
      user,
    ],
  );

  return {
    threadPane,
    desktopRightPanelContent,
  };
}
