import {
  formatDetailDate as formatDate,
  formatDetailHistoryTransition as formatHistoryTransition,
  formatDetailHistoryValue as formatHistoryValue,
} from './detailModel';

// Builds the props object for DatabaseDialogsLayer from the page view-model.
// Pure prop-mapping — every field below is a vm binding; nothing new is
// created here beyond grouping objects the dialogs already consume.
export function buildDialogsLayerProps(vm, { isMobile, theme, ui }) {
  const {
    canDatabaseWrite,
    canViewWarehouse1C,
    isAdmin,
    uploadActModalOpen,
    closeUploadActModal,
    uploadActStep,
    uploadActReminderBinding,
    uploadActReminderLoading,
    uploadActReminderError,
    openUploadActReminderTask,
    refreshUploadActReminderStatus,
    uploadActFile,
    uploadActPreviewUrl,
    uploadActPreviewError,
    openUploadActPreviewInNewTab,
    uploadActParsing,
    handleUploadActFileSelect,
    handleUploadActParse,
    uploadActError,
    setUploadActError,
    uploadActDraft,
    uploadActForm,
    uploadActAutoEmail,
    uploadActInvVerification,
    uploadActInvVerified,
    updateUploadActFormField,
    handleUploadActInvNosChange,
    setUploadActAutoEmail,
    setUploadActInvVerified,
    uploadActCommitResult,
    uploadActCommitDisabled,
    uploadActCommitting,
    handleUploadActCommit,
    uploadActEmailSubject,
    uploadActEmailBody,
    uploadActEmailRecipientOptions,
    uploadActEmailRecipients,
    uploadActEmailRecipientsInput,
    uploadActEmailRecipientsLoading,
    uploadActEmailLoading,
    uploadActEmailStatus,
    uploadActEmailError,
    uploadActEmailLastRecipients,
    uploadActEmailSummary,
    setUploadActEmailSubject,
    setUploadActEmailBody,
    setUploadActEmailRecipientsInput,
    setUploadActEmailRecipients,
    setUploadActEmailError,
    handleUploadActEmailSend,
    getUploadActEmailStatusItemSx,
    uploadActDownloading,
    uploadActDownloadError,
    setUploadActDownloadError,
    handleUploadActDownload,
    addEquipmentModalOpen,
    closeAddEquipmentModal,
    addEquipmentForm,
    addEmployeeOptions,
    addEmployeeLoading,
    selectedAddEmployeeOption,
    addEmployeeInput,
    branchOptions,
    addLocationOptions,
    addLocationsLoading,
    equipmentTypeOptions,
    statusOptions,
    addModelOptions,
    addModelsLoading,
    addUsesManualEmployee,
    addUsesManualModel,
    addEquipmentLoading,
    addEquipmentError,
    addEquipmentSuccess,
    setAddEmployeeInput,
    patchAddEquipmentForm,
    setAddEquipmentError,
    resetAddEquipmentModels,
    handleAddEquipmentSubmit,
    addConsumableModalOpen,
    closeAddConsumableModal,
    addConsumableForm,
    addConsumableLocationOptions,
    addConsumableLocationsLoading,
    consumableTypeOptions,
    addConsumableModelOptions,
    addConsumableModelsLoading,
    addConsumableLoading,
    addConsumableError,
    addConsumableSuccess,
    patchAddConsumableForm,
    setAddConsumableError,
    resetAddConsumableModels,
    handleAddConsumableSubmit,
    editConsumableQtyModal,
    editConsumableQtyValue,
    editConsumableQtyError,
    editConsumableQtyLoading,
    closeEditConsumableQtyModal,
    setEditConsumableQtyInput,
    handleEditConsumableQtySubmit,
    detailModal,
    detailForm,
    detailTab,
    detailEditMode,
    detailSaving,
    detailHasChanges,
    detailError,
    detailSuccess,
    detailActsError,
    detailHistoryError,
    modelOptions,
    detailModelsLoading,
    locationOptions,
    detailActs,
    detailActsLoading,
    detailActOpeningDocNo,
    detailHistory,
    detailHistoryLoading,
    handleCloseEquipmentDetail,
    detailOpenedFromEmployee,
    handleBackToEmployeeEquipment,
    handleDetailEditKeyDown,
    setDetailTab,
    patchDetailForm,
    setDetailError,
    setDetailSuccess,
    setDetailActsError,
    setDetailHistoryError,
    startDetailEdit,
    handleDetailCancel,
    handleDetailSave,
    setDetailQrOpen,
    handleOpenActFields,
    handleOpenEquipmentActFile,
    handleOpenEmployee,
    buildWarehouseReturnContext,
    employeeEquipmentDialog,
    handleCloseEmployeeEquipmentDialog,
    handleOpenEquipmentFromEmployee,
    detailActFieldsOpen,
    handleCloseActFields,
    detailActSelected,
    detailActSummary,
    actFilePreview,
    closeActFilePreview,
    qrScannerOpen,
    handleQrScannerClose,
    qrScannerLoading,
    qrScannerReady,
    qrScannerError,
    qrScannerResult,
    detailQrOpen,
    detailQrUrlLoading,
    detailQrUrl,
    detailQrText,
    detailQrFileName,
    qrBatchPrint,
    deleteTarget,
    deleteError,
    deleteLoading,
    closeDeleteEquipmentDialog,
    confirmDeleteEquipment,
    deleteConsumableTarget,
    deleteConsumableError,
    deleteConsumableLoading,
    closeDeleteConsumableModal,
    confirmDeleteConsumable,
    actionModal,
    selectedItems,
    actionLoading,
    actionError,
    closeActionModal,
    transferOperationMode,
    transferResult,
    transferLocationOptions,
    transferSourceDefaults,
    transferJobPolling,
    transferRetrySubmitting,
    transferEmployeeInput,
    transferEmployeeInputTrimmed,
    transferEmployeeAutocompleteOptions,
    transferEmployeeLoading,
    selectedTransferEmployeeOption,
    transferUsesManualEmployee,
    newEmployee,
    transferDepartment,
    transferDepartmentOptions,
    transferDepartmentLoading,
    transferBranchNo,
    transferLocationNo,
    transferLocationsLoading,
    transferEmailMode,
    transferManualEmail,
    transferRecipientInput,
    transferRecipientOptions,
    transferRecipient,
    transferRecipientLoading,
    transferEmailLoading,
    transferEmailStatus,
    transferEmailError,
    transferActionHandlers,
    actionWorkConsumableOptions,
    workConsumablesLoading,
    selectedWorkConsumable,
    setSelectedWorkConsumable,
    cartridgeModel,
    cartridgeHistory,
    batteryHistory,
    componentType,
    activeComponentOptions,
    setComponentType,
    componentHistory,
    cleaningHistory,
    handleActionConfirm,
  } = vm;

  return {
    isMobile,
    theme,
    ui,
    canDatabaseWrite,
    canViewWarehouse1C,
    isAdmin,
    formatDate,
    formatHistoryValue,
    formatHistoryTransition,
    uploadAct: {
      modalOpen: uploadActModalOpen,
      onClose: closeUploadActModal,
      props: {
        step: uploadActStep,
        reminder: {
          binding: uploadActReminderBinding,
          loading: uploadActReminderLoading,
          error: uploadActReminderError,
          onOpenTask: openUploadActReminderTask,
          onRefreshReminder: refreshUploadActReminderStatus,
        },
        file: {
          file: uploadActFile,
          previewUrl: uploadActPreviewUrl,
          previewError: uploadActPreviewError,
          onOpenPreview: openUploadActPreviewInNewTab,
          parsing: uploadActParsing,
          onFileSelect: handleUploadActFileSelect,
          onParse: handleUploadActParse,
        },
        error: uploadActError,
        onErrorClear: () => setUploadActError(''),
        draft: uploadActDraft,
        details: {
          form: uploadActForm,
          autoEmail: uploadActAutoEmail,
          invVerification: uploadActInvVerification,
          invVerified: uploadActInvVerified,
          onFieldChange: updateUploadActFormField,
          onInvNosChange: handleUploadActInvNosChange,
          onAutoEmailChange: setUploadActAutoEmail,
          onInvVerifiedChange: setUploadActInvVerified,
        },
        commit: {
          result: uploadActCommitResult,
          disabled: uploadActCommitDisabled,
          committing: uploadActCommitting,
          onCommit: handleUploadActCommit,
        },
        email: {
          subject: uploadActEmailSubject,
          body: uploadActEmailBody,
          recipientOptions: uploadActEmailRecipientOptions,
          recipients: uploadActEmailRecipients,
          recipientsInput: uploadActEmailRecipientsInput,
          recipientsLoading: uploadActEmailRecipientsLoading,
          loading: uploadActEmailLoading,
          status: uploadActEmailStatus,
          error: uploadActEmailError,
          lastRecipients: uploadActEmailLastRecipients,
          summary: uploadActEmailSummary,
          onSubjectChange: setUploadActEmailSubject,
          onBodyChange: setUploadActEmailBody,
          onRecipientsInputChange: setUploadActEmailRecipientsInput,
          onRecipientsChange: setUploadActEmailRecipients,
          onErrorClear: () => setUploadActEmailError(''),
          onSend: handleUploadActEmailSend,
          getStatusItemSx: getUploadActEmailStatusItemSx,
        },
        download: {
          downloading: uploadActDownloading,
          error: uploadActDownloadError,
          onErrorClear: () => setUploadActDownloadError(''),
          onDownload: handleUploadActDownload,
        },
      },
    },
    addEquipment: {
      modalOpen: addEquipmentModalOpen,
      onClose: closeAddEquipmentModal,
      props: {
        form: addEquipmentForm,
        employeeOptions: addEmployeeOptions,
        employeeLoading: addEmployeeLoading,
        selectedEmployeeOption: selectedAddEmployeeOption,
        employeeInput: addEmployeeInput,
        branchOptions,
        locationOptions: addLocationOptions,
        locationsLoading: addLocationsLoading,
        typeOptions: equipmentTypeOptions,
        statusOptions,
        modelOptions: addModelOptions,
        modelsLoading: addModelsLoading,
        usesManualEmployee: addUsesManualEmployee,
        usesManualModel: addUsesManualModel,
        loading: addEquipmentLoading,
        error: addEquipmentError,
        success: addEquipmentSuccess,
        onEmployeeInputChange: setAddEmployeeInput,
        onEmployeeSelect: setAddEmployeeInput,
        onFormPatch: patchAddEquipmentForm,
        onErrorClear: () => setAddEquipmentError(''),
        onModelsReset: resetAddEquipmentModels,
        onSubmit: handleAddEquipmentSubmit,
      },
    },
    addConsumable: {
      modalOpen: addConsumableModalOpen,
      onClose: closeAddConsumableModal,
      props: {
        form: addConsumableForm,
        branchOptions,
        locationOptions: addConsumableLocationOptions,
        locationsLoading: addConsumableLocationsLoading,
        typeOptions: consumableTypeOptions,
        modelOptions: addConsumableModelOptions,
        modelsLoading: addConsumableModelsLoading,
        loading: addConsumableLoading,
        error: addConsumableError,
        success: addConsumableSuccess,
        onFormPatch: patchAddConsumableForm,
        onErrorClear: () => setAddConsumableError(''),
        onModelsReset: resetAddConsumableModels,
        onSubmit: handleAddConsumableSubmit,
      },
    },
    editConsumableQty: {
      modal: editConsumableQtyModal,
      props: {
        item: editConsumableQtyModal.item,
        value: editConsumableQtyValue,
        error: editConsumableQtyError,
        loading: editConsumableQtyLoading,
        onClose: closeEditConsumableQtyModal,
        onValueChange: setEditConsumableQtyInput,
        onSubmit: handleEditConsumableQtySubmit,
      },
    },
    detail: {
      modal: detailModal,
      props: {
        loading: detailModal.loading,
        data: detailModal.data,
        form: detailForm,
        tab: detailTab,
        editMode: detailEditMode,
        saving: detailSaving,
        hasChanges: detailHasChanges,
        messages: {
          error: detailError,
          success: detailSuccess,
          actsError: detailActsError,
          historyError: detailHistoryError,
        },
        options: {
          statuses: statusOptions,
          types: equipmentTypeOptions,
          models: modelOptions,
          modelsLoading: detailModelsLoading,
          branches: branchOptions,
          locations: locationOptions,
        },
        acts: {
          items: detailActs,
          loading: detailActsLoading,
          openingDocNo: detailActOpeningDocNo,
        },
        history: {
          items: detailHistory,
          loading: detailHistoryLoading,
        },
        onClose: handleCloseEquipmentDetail,
        onBack: detailOpenedFromEmployee ? handleBackToEmployeeEquipment : null,
        onKeyDown: handleDetailEditKeyDown,
        onTabChange: setDetailTab,
        onFormPatch: patchDetailForm,
        onClearError: () => setDetailError(''),
        onClearSuccess: () => setDetailSuccess(''),
        onClearActsError: () => setDetailActsError(''),
        onClearHistoryError: () => setDetailHistoryError(''),
        onStartEdit: startDetailEdit,
        onCancel: handleDetailCancel,
        onSave: handleDetailSave,
        onOpenQr: () => setDetailQrOpen(true),
        onOpenActFields: handleOpenActFields,
        onOpenActFile: handleOpenEquipmentActFile,
        onOpenEmployee: handleOpenEmployee,
        buildWarehouseReturnContext,
        disableEnforceFocus: employeeEquipmentDialog.open && !detailOpenedFromEmployee,
        stackAboveParent: detailOpenedFromEmployee,
      },
    },
    employeeDialog: {
      state: employeeEquipmentDialog,
      props: {
        disableEnforceFocus: detailOpenedFromEmployee,
        onClose: handleCloseEmployeeEquipmentDialog,
        onOpenInvNo: handleOpenEquipmentFromEmployee,
        buildWarehouseReturnContext,
      },
    },
    actFields: {
      open: detailActFieldsOpen,
      props: {
        onClose: handleCloseActFields,
        selectedAct: detailActSelected,
        summary: detailActSummary,
        openingDocNo: detailActOpeningDocNo,
        onOpenFile: handleOpenEquipmentActFile,
      },
    },
    actFilePreview: {
      state: actFilePreview,
      props: {
        title: actFilePreview?.title || 'Акт',
        subtitle: actFilePreview?.subtitle || '',
        kind: actFilePreview?.kind || 'pdf',
        objectUrl: actFilePreview?.objectUrl || '',
        loading: Boolean(actFilePreview?.loading),
        error: actFilePreview?.error || '',
        onClose: closeActFilePreview,
        onDownloadOriginal: actFilePreview?.previewBlob && actFilePreview?.objectUrl ? () => {
          const link = document.createElement('a');
          link.href = actFilePreview.objectUrl;
          link.download = actFilePreview.title || 'act.pdf';
          link.click();
        } : undefined,
        canDownloadOriginal: Boolean(actFilePreview?.previewBlob),
      },
    },
    qrScanner: {
      open: qrScannerOpen,
      props: {
        onClose: handleQrScannerClose,
        loading: qrScannerLoading,
        ready: qrScannerReady,
        error: qrScannerError,
        result: qrScannerResult,
      },
    },
    detailQr: {
      open: detailQrOpen,
      props: {
        onClose: () => setDetailQrOpen(false),
        loading: detailQrUrlLoading,
        url: detailQrUrl,
        text: detailQrText,
        fileName: detailQrFileName,
      },
    },
    qrBatchPrint,
    deleteEquipment: {
      target: deleteTarget,
      props: {
        error: deleteError,
        loading: deleteLoading,
        onClose: closeDeleteEquipmentDialog,
        onConfirm: () => void confirmDeleteEquipment(),
      },
    },
    deleteConsumable: {
      target: deleteConsumableTarget,
      props: {
        error: deleteConsumableError,
        loading: deleteConsumableLoading,
        onClose: closeDeleteConsumableModal,
        onConfirm: () => void confirmDeleteConsumable(),
      },
    },
    actionDialog: {
      open: actionModal.open,
      props: {
        actionModal,
        selectedCount: selectedItems.length,
        actionLoading,
        actionError,
        onClose: () => closeActionModal(),
        transferOperationMode,
        transferResult,
        transferContentProps: {
          isMobile,
          canDatabaseWrite,
          ui,
          theme,
          branchOptions,
          locationOptions: transferLocationOptions,
          sourceDefaults: transferSourceDefaults,
          transfer: {
            mode: transferOperationMode,
            result: transferResult,
            jobPolling: transferJobPolling,
            retrySubmitting: transferRetrySubmitting,
            employeeInput: transferEmployeeInput,
            employeeInputTrimmed: transferEmployeeInputTrimmed,
            employeeOptions: transferEmployeeAutocompleteOptions,
            employeeLoading: transferEmployeeLoading,
            selectedEmployeeOption: selectedTransferEmployeeOption,
            usesManualEmployee: transferUsesManualEmployee,
            newEmployee,
            department: transferDepartment,
            departmentOptions: transferDepartmentOptions,
            departmentLoading: transferDepartmentLoading,
            branchNo: transferBranchNo,
            locationNo: transferLocationNo,
            locationsLoading: transferLocationsLoading,
          },
          email: {
            mode: transferEmailMode,
            manualEmail: transferManualEmail,
            recipientInput: transferRecipientInput,
            recipientOptions: transferRecipientOptions,
            recipient: transferRecipient,
            recipientLoading: transferRecipientLoading,
            loading: transferEmailLoading,
            status: transferEmailStatus,
            error: transferEmailError,
          },
          actions: transferActionHandlers,
        },
        maintenanceContentProps: {
          ui,
          consumableOptions: actionWorkConsumableOptions,
          consumablesLoading: workConsumablesLoading,
          selectedConsumable: selectedWorkConsumable,
          onSelectedConsumableChange: setSelectedWorkConsumable,
          cartridgeModel,
          cartridgeHistory,
          batteryHistory,
          componentType,
          componentOptions: activeComponentOptions,
          onComponentTypeChange: setComponentType,
          componentHistory,
          cleaningHistory,
          formatDate,
        },
        onConfirm: () => void handleActionConfirm(),
      },
    },
  };
}
