"""Company directory tools for ai_chat (group "directory").

Only work-directory data reaches the model: name, position, department, office,
work phones/e-mails and the current absence. Personal phones/e-mails, age, hire
date and INN are never returned here even when the employee may see them in the
portal — the answer is generated by an external LLM. The field allowlist is the
same one the org-structure page uses (``company_structure_service._safe_person``).
"""
from __future__ import annotations

import logging
from datetime import date
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator

from backend.ai_chat.tools.base import AiTool, AiToolResult
from backend.ai_chat.tools.context import (
    AiToolExecutionContext,
    DIRECTORY_TOOL_DEPARTMENT_GET,
    DIRECTORY_TOOL_PEOPLE_SEARCH,
)
from backend.ai_chat.tools.registry import ai_tool_registry

logger = logging.getLogger(__name__)

MAX_PEOPLE = 15
# Absent-only queries scan more rows before filtering.
_ABSENT_SCAN_LIMIT = 200


def _normalize_text(value: object) -> str:
    return str(value or "").strip()


def _absence_view(raw: Any, *, today: date | None = None) -> Optional[dict[str, Any]]:
    """ZUP absence ({kind, label, starts_on, returns_on}); None once the employee is back.

    The address-book cache is refreshed periodically, so a return date that has
    already come is re-checked here.
    """
    if not isinstance(raw, dict):
        return None
    starts_on = _normalize_text(raw.get("starts_on"))[:10] or None
    returns_on = _normalize_text(raw.get("returns_on"))[:10] or None
    if returns_on:
        try:
            if date.fromisoformat(returns_on) <= (today or date.today()):
                return None
        except ValueError:
            pass
    return {
        "kind": _normalize_text(raw.get("kind")) or None,
        "label": _normalize_text(raw.get("label")) or None,
        "starts_on": starts_on,
        "returns_on": returns_on,
    }


def person_view(raw: dict[str, Any]) -> dict[str, Any]:
    from backend.services.company_structure_service import _safe_person

    view = _safe_person(raw)
    view = {key: value for key, value in view.items() if value not in ("", [], None)}
    absence = _absence_view(raw.get("absence"))
    if absence:
        view["absence"] = absence
    return view


class PeopleSearchArgs(BaseModel):
    query: Optional[str] = Field(default=None, max_length=200, description="Surname/name, position, phone or e-mail")
    department: Optional[str] = Field(default=None, max_length=200, description="Exact department name to filter by")
    absent_only: bool = Field(default=False, description="Only people who are absent now (vacation, sick leave, trip)")
    limit: int = Field(default=10, ge=1, le=MAX_PEOPLE)

    @field_validator("query", "department", mode="before")
    @classmethod
    def _normalize(cls, value):
        return _normalize_text(value) or None


class DepartmentGetArgs(BaseModel):
    query: str = Field(..., min_length=2, max_length=200, description="Department name or part of it")

    @field_validator("query", mode="before")
    @classmethod
    def _normalize(cls, value):
        return _normalize_text(value)


class PeopleSearchTool(AiTool):
    tool_id = DIRECTORY_TOOL_PEOPLE_SEARCH
    description = (
        "Company phone book (1C ZUP address book): find colleagues by name, position, phone or e-mail and get "
        "position, department, office room, work phones/e-mails and current absence (vacation/sick leave with "
        "return date). Use for 'телефон Петрова', 'кто бухгалтер по зарплате', 'Иванова в отпуске?', "
        "'кто отсутствует в отделе продаж' (department + absent_only)."
    )
    input_model = PeopleSearchArgs
    stage = "checking_chat"

    def execute(self, *, context: AiToolExecutionContext, args: PeopleSearchArgs) -> AiToolResult:
        from backend.services.address_book_service import address_book_service

        if not args.query and not args.department:
            return AiToolResult(tool_id=self.tool_id, ok=False, error="Укажите имя, должность, телефон или отдел.")
        kwargs: dict[str, Any] = {}
        if args.department:
            kwargs["department"] = args.department
        try:
            payload = address_book_service.search(
                args.query or "",
                _ABSENT_SCAN_LIMIT if args.absent_only else int(args.limit),
                **kwargs,
            )
        except Exception as exc:
            logger.warning("ai directory.people.search failed: %s", type(exc).__name__)
            return AiToolResult(tool_id=self.tool_id, ok=False, error=f"Справочник сотрудников недоступен: {exc}")
        people = [person_view(item) for item in list(payload.get("items") or []) if isinstance(item, dict)]
        if args.absent_only:
            people = [person for person in people if person.get("absence")]
        total = len(people) if args.absent_only else int(payload.get("total") or len(people))
        people = people[: int(args.limit)]
        return AiToolResult(
            tool_id=self.tool_id,
            ok=True,
            data={
                "count": len(people),
                "total": total,
                "truncated": total > len(people),
                "updated_at": payload.get("updated_at") or None,
                "items": people,
            },
        )


class DepartmentGetTool(AiTool):
    tool_id = DIRECTORY_TOOL_DEPARTMENT_GET
    description = (
        "Company org structure: find a department and its head (leader name and position) and where it sits in "
        "the hierarchy. Use for 'кто руководитель бухгалтерии', 'кому подчиняется отдел логистики'."
    )
    input_model = DepartmentGetArgs
    stage = "checking_chat"

    def execute(self, *, context: AiToolExecutionContext, args: DepartmentGetArgs) -> AiToolResult:
        from backend.services.company_structure_service import get_company_structure_service

        try:
            company_structure_service = get_company_structure_service()
            payload = company_structure_service.search_directory(args.query, limit=30)
        except Exception as exc:
            logger.warning("ai directory.department.get failed: %s", type(exc).__name__)
            return AiToolResult(tool_id=self.tool_id, ok=False, error=f"Оргструктура недоступна: {exc}")
        departments = []
        for item in list(payload.get("items") or []):
            if not isinstance(item, dict) or item.get("kind") != "node":
                continue
            node = company_structure_service.get_node(_normalize_text(item.get("node_id"))) or {}
            departments.append(
                {
                    "title": _normalize_text(item.get("title")) or None,
                    "head_name": _normalize_text(node.get("person_name")) or None,
                    "head_position": _normalize_text(node.get("person_position")) or None,
                    "path": [
                        _normalize_text(part.get("title"))
                        for part in list(item.get("path") or [])
                        if isinstance(part, dict) and _normalize_text(part.get("title"))
                    ],
                }
            )
            if len(departments) >= 10:
                break
        if not departments:
            return AiToolResult(tool_id=self.tool_id, ok=False, error="Подразделение не найдено в оргструктуре.")
        return AiToolResult(tool_id=self.tool_id, ok=True, data={"count": len(departments), "items": departments})


for tool in [PeopleSearchTool(), DepartmentGetTool()]:
    ai_tool_registry.register(tool)
