export const TASKS_MOBILE_COPY = {
  tasksTitle: 'Задачи',
  analyticsTitle: 'Аналитика',
  feedTitle: 'Лента',
  listSuffix: 'задач в ленте',
  boardHint: 'Откройте карточку, чтобы увидеть детали, файлы и обсуждение.',
  analyticsHint: 'Фильтры аналитики и экспорт спрятаны в «Ещё».',
  drawerTitle: 'Ещё и фильтры',
  drawerBoardSubtitle: 'Режимы, роли, статусы и расширенные фильтры.',
  drawerAnalyticsSubtitle: 'Навигация, фильтры и экспорт аналитики.',
  closeDrawer: 'Закрыть меню задач',
  refresh: 'Обновить',
  taxonomy: 'Справочники',
  listView: 'Роль',
  all: 'Все',
  assignee: 'Исполняю',
  department: 'Отдел',
  creator: 'Созданные',
  controller: 'На контроле',
  status: 'Статус',
  focus: 'Фокус',
  advancedFilters: 'Расширенные фильтры',
  analyticsFilters: 'Фильтры аналитики',
  resetFilters: 'Сбросить фильтры',
  closeMenu: 'Закрыть меню',
  openMenu: 'Открыть ещё и фильтры',
  filtersChip: 'Фильтры',
  search: 'Поиск',
  searchPlaceholder: 'Заголовок, комментарий, участник...',
};
